/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;

/**
 * Role-specific screen for Admin users.
 * Tabs: All Transactions | Agent Management | Inventory
 *
 * @author Group 1
 */
public class AdminFrame extends javax.swing.JFrame {

    private MyLib.Admin admin;

    public AdminFrame(MyLib.Admin admin) {
        this.admin = admin;
        initComponents();
        setupUI();
        setSize(1100, 700);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        mainTabs = new javax.swing.JTabbedPane();
        jPanel_adminTxns = new javax.swing.JPanel();
        jPanel_adminTxnToolbar = new javax.swing.JPanel();
        jButton_refreshAdminTxns = new javax.swing.JButton();
        jScrollPane_adminTxns = new javax.swing.JScrollPane();
        adminTxnTable = new javax.swing.JTable();
        jPanel_adminAgentMgmt = new javax.swing.JPanel();
        jPanel_agentListToolbar = new javax.swing.JPanel();
        jButton_refreshAgents = new javax.swing.JButton();
        jScrollPane_agentList = new javax.swing.JScrollPane();
        jTable_agentList = new javax.swing.JTable();
        jPanel_agentCreateForm = new javax.swing.JPanel();
        jLabel_agentNameKey = new javax.swing.JLabel();
        jTextField_agentName = new javax.swing.JTextField();
        jLabel_agentEmailKey = new javax.swing.JLabel();
        jTextField_agentEmail = new javax.swing.JTextField();
        jLabel_agentPassKey = new javax.swing.JLabel();
        jTextField_agentPass = new javax.swing.JTextField();
        jLabel_agentCommKey = new javax.swing.JLabel();
        jTextField_agentComm = new javax.swing.JTextField();
        jButton_saveAgent = new javax.swing.JButton();
        jPanel_adminInventory = new javax.swing.JPanel();
        jPanel_invToolbar = new javax.swing.JPanel();
        jButton_refreshInventory = new javax.swing.JButton();
        jScrollPane_adminInv = new javax.swing.JScrollPane();
        adminInvTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 51, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LUMINA HOMES");

        jLabel6.setForeground(new java.awt.Color(190, 215, 240));
        jLabel6.setText("Welcome");

        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addComponent(jButton3))
                .addContainerGap())
        );

        mainTabs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jPanel_adminTxns.setBackground(new java.awt.Color(248, 249, 252));
        jPanel_adminTxns.setLayout(new java.awt.BorderLayout());

        jPanel_adminTxnToolbar.setOpaque(false);
        jPanel_adminTxnToolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton_refreshAdminTxns.setBackground(new java.awt.Color(0, 51, 204));
        jButton_refreshAdminTxns.setForeground(new java.awt.Color(255, 255, 255));
        jButton_refreshAdminTxns.setText("⟳  Refresh");
        jButton_refreshAdminTxns.setBorderPainted(false);
        jButton_refreshAdminTxns.setFocusPainted(false);
        jPanel_adminTxnToolbar.add(jButton_refreshAdminTxns);

        jPanel_adminTxns.add(jPanel_adminTxnToolbar, java.awt.BorderLayout.NORTH);

        adminTxnTable.setRowHeight(26);
        jScrollPane_adminTxns.setViewportView(adminTxnTable);

        jPanel_adminTxns.add(jScrollPane_adminTxns, java.awt.BorderLayout.CENTER);

        mainTabs.addTab("All Transactions", jPanel_adminTxns);

        // ── Agent Management tab (agent list + create agent form) ──────
        jPanel_adminAgentMgmt.setBackground(new java.awt.Color(248, 249, 252));
        jPanel_adminAgentMgmt.setLayout(new java.awt.BorderLayout());

        jPanel_agentListToolbar.setOpaque(false);
        jPanel_agentListToolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton_refreshAgents.setBackground(new java.awt.Color(0, 51, 204));
        jButton_refreshAgents.setForeground(new java.awt.Color(255, 255, 255));
        jButton_refreshAgents.setText("\u27f3  Refresh");
        jButton_refreshAgents.setBorderPainted(false);
        jButton_refreshAgents.setFocusPainted(false);
        jPanel_agentListToolbar.add(jButton_refreshAgents);

        jPanel_adminAgentMgmt.add(jPanel_agentListToolbar, java.awt.BorderLayout.NORTH);

        jTable_agentList.setRowHeight(26);
        jScrollPane_agentList.setViewportView(jTable_agentList);
        jPanel_adminAgentMgmt.add(jScrollPane_agentList, java.awt.BorderLayout.CENTER);

        // Create agent form — always visible at the bottom
        jPanel_agentCreateForm.setOpaque(false);
        jPanel_agentCreateForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Create New Agent"));

        javax.swing.JPanel agentFormFields = new javax.swing.JPanel(new java.awt.GridLayout(2, 4, 8, 8));
        agentFormFields.setOpaque(false);

        jLabel_agentNameKey.setText("Full Name:");
        jLabel_agentEmailKey.setText("Email:");
        jLabel_agentPassKey.setText("Password:");
        jLabel_agentCommKey.setText("Commission Rate:");
        jTextField_agentComm.setText("0.05");

        agentFormFields.add(jLabel_agentNameKey);  agentFormFields.add(jTextField_agentName);
        agentFormFields.add(jLabel_agentEmailKey); agentFormFields.add(jTextField_agentEmail);
        agentFormFields.add(jLabel_agentPassKey);  agentFormFields.add(jTextField_agentPass);
        agentFormFields.add(jLabel_agentCommKey);  agentFormFields.add(jTextField_agentComm);

        javax.swing.JPanel agentFormBtns = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        agentFormBtns.setOpaque(false);

        jButton_saveAgent.setBackground(new java.awt.Color(0, 51, 204));
        jButton_saveAgent.setForeground(new java.awt.Color(255, 255, 255));
        jButton_saveAgent.setText("Create Agent");
        jButton_saveAgent.setBorderPainted(false);
        jButton_saveAgent.setFocusPainted(false);
        agentFormBtns.add(jButton_saveAgent);

        jPanel_agentCreateForm.setLayout(new java.awt.BorderLayout());
        jPanel_agentCreateForm.add(agentFormFields, java.awt.BorderLayout.CENTER);
        jPanel_agentCreateForm.add(agentFormBtns, java.awt.BorderLayout.SOUTH);

        jPanel_adminAgentMgmt.add(jPanel_agentCreateForm, java.awt.BorderLayout.SOUTH);

        mainTabs.addTab("Agent Management", jPanel_adminAgentMgmt);

        jPanel_adminInventory.setBackground(new java.awt.Color(248, 249, 252));
        jPanel_adminInventory.setLayout(new java.awt.BorderLayout());

        jPanel_invToolbar.setOpaque(false);
        jPanel_invToolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton_refreshInventory.setBackground(new java.awt.Color(0, 51, 204));
        jButton_refreshInventory.setForeground(new java.awt.Color(255, 255, 255));
        jButton_refreshInventory.setText("\u27f3  Refresh Inventory");
        jButton_refreshInventory.setBorderPainted(false);
        jButton_refreshInventory.setFocusPainted(false);
        jPanel_invToolbar.add(jButton_refreshInventory);

        jPanel_adminInventory.add(jPanel_invToolbar, java.awt.BorderLayout.NORTH);

        adminInvTable.setRowHeight(26);
        jScrollPane_adminInv.setViewportView(adminInvTable);

        jPanel_adminInventory.add(jScrollPane_adminInv, java.awt.BorderLayout.CENTER);

        mainTabs.addTab("Inventory", jPanel_adminInventory);

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 1553, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    // ── Non-GEN fields ──────────────────────────────────────────────────────
    private javax.swing.table.DefaultTableModel adminTxnModel;
    private javax.swing.table.DefaultTableModel adminInvModel;
    private javax.swing.table.DefaultTableModel agentListModel;
    private javax.swing.JLabel statusLabel;

    private static final java.awt.Color BG           = new java.awt.Color(248, 249, 252);
    private static final java.awt.Color HEADER_COLOR = new java.awt.Color(0, 51, 204);

    // ── Setup ──────────────────────────────────────────────────────────────
    private void setupUI() {
        // Status bar label
        jPanel3.setLayout(new java.awt.BorderLayout());
        statusLabel = new javax.swing.JLabel();
        statusLabel.setForeground(java.awt.Color.WHITE);
        statusLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        jPanel3.add(statusLabel, java.awt.BorderLayout.WEST);

        // User labels
        jLabel6.setText(admin.getName() + "  |  Admin");
        statusLabel.setText("  " + admin.getName() + "  |  " + java.time.LocalDate.now());

        // All Transactions table model
        adminTxnModel = new javax.swing.table.DefaultTableModel(
            new String[]{"TXN ID","Buyer","Agent","Block","Lot #","Model","Final TCP","Payment","Discount","Status","Remark"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        adminTxnTable.setModel(adminTxnModel);

        // Inventory table model
        adminInvModel = new javax.swing.table.DefaultTableModel(
            new String[]{"Block","Lot #","Model","Total Contract Price","Floor Area","Lot Area","Phase","Status"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        adminInvTable.setModel(adminInvModel);

        // Agent list table model
        agentListModel = new javax.swing.table.DefaultTableModel(
            new String[]{"Agent ID","Name","Email","Commission Rate","Assigned Buyers"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        jTable_agentList.setModel(agentListModel);

        // Column widths
        setColWidths(adminTxnTable,  90, 120, 110, 50, 50, 120, 130, 100, 100, 85, 130);
        setColWidths(adminInvTable,  55, 55, 140, 160, 85, 80, 85, 90);
        setColWidths(jTable_agentList, 90, 150, 190, 110, 100);

        // Action listeners
        jButton_refreshAdminTxns.addActionListener(e -> refreshAdminTxnTable());
        jButton_refreshInventory.addActionListener(e -> refreshAdminInventory());
        jButton_refreshAgents.addActionListener(e -> refreshAgentListTable());

        jButton_saveAgent.addActionListener(e -> {
            String name  = jTextField_agentName.getText().trim();
            String email = jTextField_agentEmail.getText().trim();
            String pass  = jTextField_agentPass.getText().trim();
            String commS = jTextField_agentComm.getText().trim();
            if (name.isEmpty() || email.isEmpty() || pass.isEmpty() || commS.isEmpty()) {
                showMsg("All fields are required."); return;
            }
            AppContext actx = AppContext.getInstance();
            if (actx.emailExists(email)) {
                showMsg("An account with this email already exists."); return;
            }
            double comm;
            try { comm = Double.parseDouble(commS); }
            catch (NumberFormatException ex) { showMsg("Commission Rate must be a number (e.g. 0.05)."); return; }
            String id = "AGT" + String.format("%03d", actx.getAgents().size() + 1);
            MyLib.Agent newAgent = new MyLib.Agent(name, email, pass, id, comm, actx.getSubdivision());
            actx.registerAgent(newAgent);
            jTextField_agentName.setText("");
            jTextField_agentEmail.setText("");
            jTextField_agentPass.setText("");
            jTextField_agentComm.setText("0.05");
            showMsg("Agent " + name + " created successfully.");
            refreshAgentListTable();
        });

        // Initial data
        refreshAdminTxnTable();
        refreshAdminInventory();
        refreshAgentListTable();
    }

    // ── All Transactions helpers ────────────────────────────────────────────

    private void refreshAdminTxnTable() {
        if (adminTxnModel == null) return;
        AppContext ctx = AppContext.getInstance();
        adminTxnModel.setRowCount(0);
        for (MyLib.Transaction t : ctx.getAllTransactions()) {
            MyLib.Lot lot = t.getLot();
            adminTxnModel.addRow(new Object[]{
                t.getTransactionID(),
                t.getBuyer() != null ? t.getBuyer().getName() : "\u2014",
                t.getAssignedAgent() != null ? t.getAssignedAgent().getName() : "\u2014",
                lot != null ? lot.getBlkNum() : "\u2014",
                lot != null ? lot.getLotNum() : "\u2014",
                lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014",
                "\u20b1" + String.format("%,.2f", t.getFinalTCP()),
                paymentLabel(t.getPaymentMethod()),
                t.getDiscount() != null ? t.getDiscount().getDiscountDescription() : "None",
                t.getTransactionStatus(),
                t.getRemark() != null && !t.getRemark().isEmpty() ? t.getRemark() : "\u2014"
            });
        }
    }

    // ── Inventory helpers ───────────────────────────────────────────────────

    private void refreshAdminInventory() {
        if (adminInvModel == null) return;
        AppContext ctx = AppContext.getInstance();
        adminInvModel.setRowCount(0);
        for (MyLib.Block block : ctx.getSubdivision().getBlocks()) {
            for (MyLib.Lot lot : block.getLots()) {
                MyLib.PropertyUnit u = lot.getHouseModel();
                adminInvModel.addRow(new Object[]{
                    lot.getBlkNum(), lot.getLotNum(),
                    u != null ? u.getModelName() : "\u2014",
                    u != null ? "\u20b1" + String.format("%,.0f", u.getEstimatedTCP()) : "\u2014",
                    u != null ? u.getFloorArea() + " sqm" : "\u2014",
                    u != null ? u.getLotArea()   + " sqm" : "\u2014",
                    u != null ? u.getPhase() : "\u2014",
                    lot.getTransactionStatus()
                });
            }
        }
    }

    // ── Manage Agents helpers ───────────────────────────────────────────────

    private void refreshAgentListTable() {
        if (agentListModel == null) return;
        agentListModel.setRowCount(0);
        for (MyLib.Agent a : AppContext.getInstance().getAgents()) {
            java.util.Set<String> buyerIds = new java.util.HashSet<>();
            for (MyLib.Transaction t : a.getHandledTransactions())
                if (t.getBuyer() != null) buyerIds.add(t.getBuyer().getBuyerId());
            agentListModel.addRow(new Object[]{
                a.getAgentId(), a.getName(), a.getEmail(),
                String.format("%.2f%%", a.getCommissionRate() * 100),
                buyerIds.size()
            });
        }
    }

    // ── Shared helpers ──────────────────────────────────────────────────────

    private void setColWidths(javax.swing.JTable t, int... widths) {
        for (int i = 0; i < widths.length && i < t.getColumnCount(); i++)
            t.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
    }

    private String paymentLabel(MyLib.PaymentMethod pm) {
        if (pm == null)                  return "\u2014";
        if (pm instanceof MyLib.Cash)    return "Cash";
        if (pm instanceof MyLib.Bank)    return "Bank Financing";
        if (pm instanceof MyLib.Pagibig) return "Pag-IBIG";
        if (pm instanceof MyLib.EMI)     return "EMI (In-House)";
        return pm.getClass().getSimpleName();
    }

    private void showMsg(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminInvTable;
    private javax.swing.JTable adminTxnTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_refreshAdminTxns;
    private javax.swing.JButton jButton_refreshAgents;
    private javax.swing.JButton jButton_refreshInventory;
    private javax.swing.JButton jButton_saveAgent;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_agentCommKey;
    private javax.swing.JLabel jLabel_agentEmailKey;
    private javax.swing.JLabel jLabel_agentNameKey;
    private javax.swing.JLabel jLabel_agentPassKey;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_adminAgentMgmt;
    private javax.swing.JPanel jPanel_adminInventory;
    private javax.swing.JPanel jPanel_adminTxnToolbar;
    private javax.swing.JPanel jPanel_adminTxns;
    private javax.swing.JPanel jPanel_agentCreateForm;
    private javax.swing.JPanel jPanel_agentListToolbar;
    private javax.swing.JPanel jPanel_invToolbar;
    private javax.swing.JScrollPane jScrollPane_adminInv;
    private javax.swing.JScrollPane jScrollPane_adminTxns;
    private javax.swing.JScrollPane jScrollPane_agentList;
    private javax.swing.JTable jTable_agentList;
    private javax.swing.JTextField jTextField_agentComm;
    private javax.swing.JTextField jTextField_agentEmail;
    private javax.swing.JTextField jTextField_agentName;
    private javax.swing.JTextField jTextField_agentPass;
    private javax.swing.JTabbedPane mainTabs;
    // End of variables declaration//GEN-END:variables
}
