/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;

/**
 * Role-specific screen for Admin users.
 * Tabs: All Transactions | Agent Management | Inventory
 *
 * @author Group 1
 */
public class AdminFrame extends javax.swing.JFrame {

    private MyLib.Admin admin;

    public AdminFrame(MyLib.Admin admin) {
        this.admin = admin;
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        mainTabs = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 51, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LUMINA HOMES");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 215, 240));
        jLabel6.setText("Welcome");

        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addComponent(jButton3))
                .addContainerGap())
        );

        mainTabs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainTabs)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    // ── Setup ──────────────────────────────────────────────────────────────

    private void setupUI() {
        jPanel3.setLayout(new java.awt.BorderLayout());
        statusLabel = new javax.swing.JLabel();
        statusLabel.setForeground(java.awt.Color.WHITE);
        statusLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        jPanel3.add(statusLabel, java.awt.BorderLayout.WEST);

        jLabel6.setText(admin.getName() + "  |  Admin");
        statusLabel.setText("  " + admin.getName() + "  |  " + java.time.LocalDate.now());

        mainTabs.addTab("All Transactions", buildAdminTransactionsTab());
        mainTabs.addTab("Agent Management", buildAdminAgentMgmtTab());
        mainTabs.addTab("Inventory",        buildAdminInventoryTab());

        setSize(1100, 700);
        setLocationRelativeTo(null);
    }

    // ─────────────────────────────────────────────────────────────────────
    // ADMIN TAB 1: All Transactions
    // ─────────────────────────────────────────────────────────────────────

    private javax.swing.table.DefaultTableModel adminTxnModel;

    private javax.swing.JPanel buildAdminTransactionsTab() {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(0, 6));
        panel.setBackground(BG);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        String[] cols = {"TXN ID", "Buyer", "Agent", "Block", "Lot #", "Model",
                         "Final TCP", "Payment", "Discount", "Status", "Remark"};
        adminTxnModel = nonEditableModel(cols);
        javax.swing.JTable table = styledTable(adminTxnModel);
        setColWidths(table, 90, 120, 110, 50, 50, 120, 130, 100, 100, 85, 130);

        javax.swing.JButton refresh = tabBtn("\u27f3  Refresh");
        refresh.addActionListener(e -> refreshAdminTxnTable());
        javax.swing.JPanel toolbar = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 6, 0));
        toolbar.setOpaque(false);
        toolbar.add(refresh);

        panel.add(toolbar, java.awt.BorderLayout.NORTH);
        panel.add(new javax.swing.JScrollPane(table), java.awt.BorderLayout.CENTER);
        refreshAdminTxnTable();
        return panel;
    }

    private void refreshAdminTxnTable() {
        if (adminTxnModel == null) return;
        AppContext ctx = AppContext.getInstance();
        adminTxnModel.setRowCount(0);
        for (MyLib.Transaction t : ctx.getAllTransactions()) {
            MyLib.Lot lot = t.getLot();
            adminTxnModel.addRow(new Object[]{
                t.getTransactionID(),
                t.getBuyer() != null ? t.getBuyer().getName() : "\u2014",
                t.getAssignedAgent() != null ? t.getAssignedAgent().getName() : "\u2014",
                lot != null ? lot.getBlkNum() : "\u2014",
                lot != null ? lot.getLotNum() : "\u2014",
                lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014",
                "\u20b1" + String.format("%,.2f", t.getFinalTCP()),
                paymentLabel(t.getPaymentMethod()),
                t.getDiscount() != null ? t.getDiscount().getDiscountDescription() : "None",
                t.getTransactionStatus(),
                t.getRemark() != null && !t.getRemark().isEmpty() ? t.getRemark() : "\u2014"
            });
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // ADMIN TAB 2: Agent Management
    // ─────────────────────────────────────────────────────────────────────

    private javax.swing.table.DefaultTableModel adminAssignModel;

    private javax.swing.JPanel buildAdminAgentMgmtTab() {
        javax.swing.JPanel outer = new javax.swing.JPanel(new java.awt.BorderLayout(0, 8));
        outer.setBackground(BG);
        outer.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        String[] cols = {"Agent", "Buyer", "TXN ID", "Block", "Lot #", "Model", "Status"};
        adminAssignModel = nonEditableModel(cols);
        javax.swing.JTable table = styledTable(adminAssignModel);
        setColWidths(table, 130, 130, 90, 50, 50, 140, 90);

        javax.swing.JPanel reassignBar = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 4));
        reassignBar.setBackground(new java.awt.Color(235, 240, 248));
        reassignBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(210, 218, 230)));
        javax.swing.JTextField txnField = new javax.swing.JTextField(10);
        javax.swing.JComboBox<String> agentCombo = buildAgentCombo();
        javax.swing.JButton reassignBtn = tabBtn("Reassign");
        reassignBtn.addActionListener(e -> {
            String txnId = txnField.getText().trim();
            if (txnId.isEmpty() || agentCombo.getSelectedIndex() < 0) {
                showMsg("Enter a TXN ID and select an agent."); return;
            }
            AppContext ctx = AppContext.getInstance();
            MyLib.Transaction target = null;
            for (MyLib.Transaction t : ctx.getAllTransactions())
                if (t.getTransactionID().equalsIgnoreCase(txnId)) { target = t; break; }
            if (target == null) { showMsg("Transaction not found: " + txnId); return; }
            MyLib.Agent newAgent = ctx.getAgents().get(agentCombo.getSelectedIndex());
            target.setAssignedAgent(newAgent);
            if (!newAgent.getHandledTransactions().contains(target))
                newAgent.addPendingTransaction(target);
            showMsg("Reassigned " + txnId + " to " + newAgent.getName());
            refreshAdminAssignTable();
        });
        javax.swing.JButton refresh = tabBtn("\u27f3  Refresh");
        refresh.addActionListener(e -> refreshAdminAssignTable());
        reassignBar.add(new javax.swing.JLabel("TXN ID:")); reassignBar.add(txnField);
        reassignBar.add(new javax.swing.JLabel("Reassign to Agent:")); reassignBar.add(agentCombo);
        reassignBar.add(reassignBtn); reassignBar.add(refresh);

        outer.add(reassignBar, java.awt.BorderLayout.NORTH);
        outer.add(new javax.swing.JScrollPane(table), java.awt.BorderLayout.CENTER);
        refreshAdminAssignTable();
        return outer;
    }

    private javax.swing.JComboBox<String> buildAgentCombo() {
        java.util.List<MyLib.Agent> agents = AppContext.getInstance().getAgents();
        String[] names = new String[agents.size()];
        for (int i = 0; i < agents.size(); i++) names[i] = agents.get(i).getName();
        return new javax.swing.JComboBox<>(names);
    }

    private void refreshAdminAssignTable() {
        if (adminAssignModel == null) return;
        AppContext ctx = AppContext.getInstance();
        adminAssignModel.setRowCount(0);
        for (MyLib.Transaction t : ctx.getAllTransactions()) {
            MyLib.Lot lot = t.getLot();
            adminAssignModel.addRow(new Object[]{
                t.getAssignedAgent() != null ? t.getAssignedAgent().getName() : "\u2014",
                t.getBuyer() != null ? t.getBuyer().getName() : "\u2014",
                t.getTransactionID(),
                lot != null ? lot.getBlkNum() : "\u2014",
                lot != null ? lot.getLotNum() : "\u2014",
                lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014",
                t.getTransactionStatus()
            });
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // ADMIN TAB 3: Inventory
    // ─────────────────────────────────────────────────────────────────────

    private javax.swing.table.DefaultTableModel adminInvModel;

    private javax.swing.JPanel buildAdminInventoryTab() {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(0, 6));
        panel.setBackground(BG);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        String[] cols = {"Block", "Lot #", "Model", "Total Contract Price",
                         "Floor Area", "Lot Area", "Phase", "Status"};
        adminInvModel = nonEditableModel(cols);
        javax.swing.JTable table = styledTable(adminInvModel);
        setColWidths(table, 55, 55, 140, 160, 85, 80, 85, 90);

        javax.swing.JButton refresh = tabBtn("\u27f3  Refresh Inventory");
        refresh.addActionListener(e -> refreshAdminInventory());
        javax.swing.JPanel toolbar = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 6, 0));
        toolbar.setOpaque(false);
        toolbar.add(refresh);

        panel.add(toolbar, java.awt.BorderLayout.NORTH);
        panel.add(new javax.swing.JScrollPane(table), java.awt.BorderLayout.CENTER);
        refreshAdminInventory();
        return panel;
    }

    private void refreshAdminInventory() {
        if (adminInvModel == null) return;
        AppContext ctx = AppContext.getInstance();
        adminInvModel.setRowCount(0);
        for (MyLib.Block block : ctx.getSubdivision().getBlocks()) {
            for (MyLib.Lot lot : block.getLots()) {
                MyLib.PropertyUnit u = lot.getHouseModel();
                adminInvModel.addRow(new Object[]{
                    lot.getBlkNum(), lot.getLotNum(),
                    u != null ? u.getModelName() : "\u2014",
                    u != null ? "\u20b1" + String.format("%,.0f", u.getEstimatedTCP()) : "\u2014",
                    u != null ? u.getFloorArea() + " sqm" : "\u2014",
                    u != null ? u.getLotArea()   + " sqm" : "\u2014",
                    u != null ? u.getPhase() : "\u2014",
                    lot.getTransactionStatus()
                });
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Shared helpers
    // ─────────────────────────────────────────────────────────────────────

    private static final java.awt.Color BG           = new java.awt.Color(248, 249, 252);
    private static final java.awt.Color HEADER_COLOR = new java.awt.Color(0, 51, 204);

    private javax.swing.JLabel statusLabel;

    private javax.swing.JButton tabBtn(String text) {
        javax.swing.JButton b = new javax.swing.JButton(text);
        b.setBackground(HEADER_COLOR);
        b.setForeground(java.awt.Color.WHITE);
        b.setFocusPainted(false);
        b.setBorderPainted(false);
        b.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        return b;
    }

    private javax.swing.table.DefaultTableModel nonEditableModel(String[] cols) {
        return new javax.swing.table.DefaultTableModel(cols, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
    }

    private javax.swing.JTable styledTable(javax.swing.table.DefaultTableModel m) {
        javax.swing.JTable t = new javax.swing.JTable(m);
        t.setRowHeight(26);
        t.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        t.setSelectionBackground(new java.awt.Color(210, 228, 252));
        t.setGridColor(new java.awt.Color(220, 220, 220));
        t.setShowGrid(true);
        t.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        t.getTableHeader().setBackground(HEADER_COLOR);
        t.getTableHeader().setForeground(java.awt.Color.WHITE);
        t.getTableHeader().setReorderingAllowed(false);
        return t;
    }

    private void setColWidths(javax.swing.JTable t, int... widths) {
        for (int i = 0; i < widths.length && i < t.getColumnCount(); i++)
            t.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
    }

    private String paymentLabel(MyLib.PaymentMethod pm) {
        if (pm == null)              return "\u2014";
        if (pm instanceof MyLib.Cash)    return "Cash";
        if (pm instanceof MyLib.Bank)    return "Bank Financing";
        if (pm instanceof MyLib.Pagibig) return "Pag-IBIG";
        if (pm instanceof MyLib.EMI)     return "EMI (In-House)";
        return pm.getClass().getSimpleName();
    }

    private void showMsg(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane mainTabs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
