/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;

/**
 * Role-specific screen for Agent users.
 * Tabs: Pending Queue | History
 *
 * @author Group 1
 */
public class AgentFrame extends javax.swing.JFrame {

    private MyLib.Agent agent;

    public AgentFrame(MyLib.Agent agent) {
        this.agent = agent;
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        mainTabs = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 51, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LUMINA HOMES");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 215, 240));
        jLabel6.setText("Welcome");

        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addComponent(jButton3))
                .addContainerGap())
        );

        mainTabs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainTabs)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    // ── Setup ──────────────────────────────────────────────────────────────

    private void setupUI() {
        jPanel3.setLayout(new java.awt.BorderLayout());
        statusLabel = new javax.swing.JLabel();
        statusLabel.setForeground(java.awt.Color.WHITE);
        statusLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        jPanel3.add(statusLabel, java.awt.BorderLayout.WEST);

        jLabel6.setText(agent.getName() + "  |  Agent");
        statusLabel.setText("  " + agent.getName() + "  |  " + java.time.LocalDate.now());

        mainTabs.addTab("Pending Queue", buildAgentPendingTab());
        mainTabs.addTab("History",       buildAgentHistoryTab());

        setSize(1100, 700);
        setLocationRelativeTo(null);
    }

    // ─────────────────────────────────────────────────────────────────────
    // AGENT TAB 1: Pending Queue
    // ─────────────────────────────────────────────────────────────────────

    private javax.swing.table.DefaultTableModel agentPendingModel;
    private javax.swing.JTable agentPendingTable;
    private javax.swing.JLabel pdTxnId, pdBuyer, pdBlkLot, pdModel,
                               pdTCP, pdPayMethod, pdLoanTerm, pdDiscount;
    private javax.swing.JButton approveBtn, rejectBtn;
    private MyLib.Transaction   selectedPendingTxn = null;

    private javax.swing.JPanel buildAgentPendingTab() {
        String[] cols = {"TXN ID", "Buyer", "Block", "Lot #", "Model",
                         "Final TCP", "Payment", "Loan Term", "Discount"};
        agentPendingModel = nonEditableModel(cols);
        agentPendingTable = styledTable(agentPendingModel);
        agentPendingTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        setColWidths(agentPendingTable, 90, 130, 50, 50, 130, 120, 110, 70, 110);

        javax.swing.JScrollPane topScroll = new javax.swing.JScrollPane(agentPendingTable);

        // Detail panel
        javax.swing.JPanel detailPanel = new javax.swing.JPanel(new java.awt.BorderLayout(0, 6));
        detailPanel.setBackground(java.awt.Color.WHITE);
        detailPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(210, 218, 230)),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));

        javax.swing.JLabel detTitle = new javax.swing.JLabel("Transaction Details");
        detTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        detTitle.setForeground(HEADER_COLOR);

        javax.swing.JPanel grid = new javax.swing.JPanel(new java.awt.GridLayout(0, 2, 8, 4));
        grid.setOpaque(false);
        pdTxnId    = detLbl(); pdBuyer     = detLbl();
        pdBlkLot   = detLbl(); pdModel     = detLbl();
        pdTCP      = detLbl(); pdPayMethod = detLbl();
        pdLoanTerm = detLbl(); pdDiscount  = detLbl();
        addDetRow(grid, "TXN ID",         pdTxnId);
        addDetRow(grid, "Buyer",          pdBuyer);
        addDetRow(grid, "Block / Lot",    pdBlkLot);
        addDetRow(grid, "House Model",    pdModel);
        addDetRow(grid, "Final TCP",      pdTCP);
        addDetRow(grid, "Payment Method", pdPayMethod);
        addDetRow(grid, "Loan Term",      pdLoanTerm);
        addDetRow(grid, "Discount",       pdDiscount);

        approveBtn = new javax.swing.JButton("Approve");
        rejectBtn  = new javax.swing.JButton("Reject");
        styleActionButton(approveBtn, new java.awt.Color(34, 120, 34));
        styleActionButton(rejectBtn,  new java.awt.Color(160, 40, 40));
        approveBtn.setEnabled(false);
        rejectBtn.setEnabled(false);

        approveBtn.addActionListener(e -> {
            if (selectedPendingTxn == null) return;
            agent.approveTransaction(selectedPendingTxn);
            showMsg("Transaction " + selectedPendingTxn.getTransactionID() + " approved.");
            selectedPendingTxn = null;
            clearPendingDetail();
            approveBtn.setEnabled(false); rejectBtn.setEnabled(false);
            refreshAgentPendingTable(); refreshAgentHistoryTable();
        });

        rejectBtn.addActionListener(e -> {
            if (selectedPendingTxn == null) return;
            javax.swing.JTextArea reasonArea = new javax.swing.JTextArea(4, 30);
            reasonArea.setLineWrap(true); reasonArea.setWrapStyleWord(true);
            int res = javax.swing.JOptionPane.showConfirmDialog(this,
                new javax.swing.JScrollPane(reasonArea), "Enter rejection reason:",
                javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
            if (res == javax.swing.JOptionPane.OK_OPTION) {
                agent.rejectTransaction(selectedPendingTxn,
                    reasonArea.getText().trim().isEmpty() ? "Rejected by agent" : reasonArea.getText().trim());
                showMsg("Transaction " + selectedPendingTxn.getTransactionID() + " rejected.");
                selectedPendingTxn = null;
                clearPendingDetail();
                approveBtn.setEnabled(false); rejectBtn.setEnabled(false);
                refreshAgentPendingTable(); refreshAgentHistoryTable();
            }
        });

        agentPendingTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = agentPendingTable.getSelectedRow();
                java.util.List<MyLib.Transaction> pending = agent.getPendingTransactions();
                if (row >= 0 && row < pending.size()) {
                    selectedPendingTxn = pending.get(row);
                    showPendingDetail(selectedPendingTxn);
                    approveBtn.setEnabled(true); rejectBtn.setEnabled(true);
                } else {
                    selectedPendingTxn = null; clearPendingDetail();
                    approveBtn.setEnabled(false); rejectBtn.setEnabled(false);
                }
            }
        });

        javax.swing.JPanel actionBar = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 4));
        actionBar.setOpaque(false);
        actionBar.add(approveBtn); actionBar.add(rejectBtn);

        detailPanel.add(detTitle,  java.awt.BorderLayout.NORTH);
        detailPanel.add(grid,      java.awt.BorderLayout.CENTER);
        detailPanel.add(actionBar, java.awt.BorderLayout.SOUTH);

        javax.swing.JSplitPane split = new javax.swing.JSplitPane(
            javax.swing.JSplitPane.VERTICAL_SPLIT,
            topScroll, new javax.swing.JScrollPane(detailPanel));
        split.setResizeWeight(0.60);
        split.setDividerSize(5);
        split.setBorder(null);

        javax.swing.JPanel wrapper = new javax.swing.JPanel(new java.awt.BorderLayout());
        wrapper.setBackground(BG);
        wrapper.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        wrapper.add(split, java.awt.BorderLayout.CENTER);

        refreshAgentPendingTable();
        return wrapper;
    }

    private void refreshAgentPendingTable() {
        if (agentPendingModel == null) return;
        agentPendingModel.setRowCount(0);
        for (MyLib.Transaction t : agent.getPendingTransactions()) {
            MyLib.Lot lot = t.getLot();
            agentPendingModel.addRow(new Object[]{
                t.getTransactionID(),
                t.getBuyer() != null ? t.getBuyer().getName() : "\u2014",
                lot != null ? lot.getBlkNum() : "\u2014",
                lot != null ? lot.getLotNum() : "\u2014",
                lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014",
                "\u20b1" + String.format("%,.2f", t.getFinalTCP()),
                paymentLabel(t.getPaymentMethod()),
                t.getLoanTerm() > 0 ? t.getLoanTerm() + " yr" : "\u2014",
                t.getDiscount() != null ? t.getDiscount().getDiscountDescription() : "None"
            });
        }
    }

    private void showPendingDetail(MyLib.Transaction t) {
        MyLib.Lot lot = t.getLot();
        pdTxnId.setText(t.getTransactionID());
        pdBuyer.setText(t.getBuyer() != null ? t.getBuyer().getName() : "\u2014");
        pdBlkLot.setText(lot != null ? "Block " + lot.getBlkNum() + "  Lot " + lot.getLotNum() : "\u2014");
        pdModel.setText(lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014");
        pdTCP.setText("\u20b1" + String.format("%,.2f", t.getFinalTCP()));
        pdPayMethod.setText(paymentLabel(t.getPaymentMethod()));
        pdLoanTerm.setText(t.getLoanTerm() > 0 ? t.getLoanTerm() + " years" : "\u2014");
        pdDiscount.setText(t.getDiscount() != null ? t.getDiscount().getDiscountDescription() : "None");
    }

    private void clearPendingDetail() {
        for (javax.swing.JLabel lbl : new javax.swing.JLabel[]{
                pdTxnId, pdBuyer, pdBlkLot, pdModel, pdTCP, pdPayMethod, pdLoanTerm, pdDiscount})
            if (lbl != null) lbl.setText("\u2014");
    }

    // ─────────────────────────────────────────────────────────────────────
    // AGENT TAB 2: History
    // ─────────────────────────────────────────────────────────────────────

    private javax.swing.table.DefaultTableModel agentHistoryModel;

    private javax.swing.JPanel buildAgentHistoryTab() {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(0, 6));
        panel.setBackground(BG);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        String[] cols = {"TXN ID", "Buyer", "Block", "Lot #", "Model",
                         "Final TCP", "Payment", "Loan Term", "Status", "Remark"};
        agentHistoryModel = nonEditableModel(cols);
        javax.swing.JTable table = styledTable(agentHistoryModel);
        setColWidths(table, 90, 130, 50, 50, 130, 120, 110, 70, 85, 140);

        javax.swing.JButton refresh = tabBtn("\u27f3  Refresh");
        refresh.addActionListener(e -> refreshAgentHistoryTable());
        javax.swing.JPanel toolbar = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 6, 0));
        toolbar.setOpaque(false);
        toolbar.add(refresh);

        panel.add(toolbar, java.awt.BorderLayout.NORTH);
        panel.add(new javax.swing.JScrollPane(table), java.awt.BorderLayout.CENTER);

        refreshAgentHistoryTable();
        return panel;
    }

    private void refreshAgentHistoryTable() {
        if (agentHistoryModel == null) return;
        agentHistoryModel.setRowCount(0);
        for (MyLib.Transaction t : agent.getApprovedTransactions()) {
            MyLib.Lot lot = t.getLot();
            agentHistoryModel.addRow(new Object[]{
                t.getTransactionID(),
                t.getBuyer() != null ? t.getBuyer().getName() : "\u2014",
                lot != null ? lot.getBlkNum() : "\u2014",
                lot != null ? lot.getLotNum() : "\u2014",
                lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014",
                "\u20b1" + String.format("%,.2f", t.getFinalTCP()),
                paymentLabel(t.getPaymentMethod()),
                t.getLoanTerm() > 0 ? t.getLoanTerm() + " yr" : "\u2014",
                t.getTransactionStatus(),
                t.getRemark() != null && !t.getRemark().isEmpty() ? t.getRemark() : "\u2014"
            });
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Shared helpers
    // ─────────────────────────────────────────────────────────────────────

    private static final java.awt.Color BG           = new java.awt.Color(248, 249, 252);
    private static final java.awt.Color HEADER_COLOR = new java.awt.Color(0, 51, 204);

    private javax.swing.JLabel statusLabel;

    private javax.swing.JButton tabBtn(String text) {
        javax.swing.JButton b = new javax.swing.JButton(text);
        b.setBackground(HEADER_COLOR);
        b.setForeground(java.awt.Color.WHITE);
        b.setFocusPainted(false);
        b.setBorderPainted(false);
        b.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        return b;
    }

    private void styleActionButton(javax.swing.JButton b, java.awt.Color bg) {
        b.setBackground(bg);
        b.setForeground(java.awt.Color.WHITE);
        b.setFocusPainted(false);
        b.setBorderPainted(false);
        b.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
    }

    private javax.swing.JLabel detLbl() {
        javax.swing.JLabel l = new javax.swing.JLabel("\u2014");
        l.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        return l;
    }

    private void addDetRow(javax.swing.JPanel grid, String key, javax.swing.JLabel val) {
        javax.swing.JLabel k = new javax.swing.JLabel(key + ":");
        k.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        k.setForeground(new java.awt.Color(80, 80, 80));
        grid.add(k); grid.add(val);
    }

    private javax.swing.table.DefaultTableModel nonEditableModel(String[] cols) {
        return new javax.swing.table.DefaultTableModel(cols, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
    }

    private javax.swing.JTable styledTable(javax.swing.table.DefaultTableModel m) {
        javax.swing.JTable t = new javax.swing.JTable(m);
        t.setRowHeight(26);
        t.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        t.setSelectionBackground(new java.awt.Color(210, 228, 252));
        t.setGridColor(new java.awt.Color(220, 220, 220));
        t.setShowGrid(true);
        t.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        t.getTableHeader().setBackground(HEADER_COLOR);
        t.getTableHeader().setForeground(java.awt.Color.WHITE);
        t.getTableHeader().setReorderingAllowed(false);
        return t;
    }

    private void setColWidths(javax.swing.JTable t, int... widths) {
        for (int i = 0; i < widths.length && i < t.getColumnCount(); i++)
            t.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
    }

    private String paymentLabel(MyLib.PaymentMethod pm) {
        if (pm == null)              return "\u2014";
        if (pm instanceof MyLib.Cash)    return "Cash";
        if (pm instanceof MyLib.Bank)    return "Bank Financing";
        if (pm instanceof MyLib.Pagibig) return "Pag-IBIG";
        if (pm instanceof MyLib.EMI)     return "EMI (In-House)";
        return pm.getClass().getSimpleName();
    }

    private void showMsg(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane mainTabs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
