/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;

/**
 * Role-specific screen for Agent users.
 * Tabs: Pending Queue | History
 *
 * @author Group 1
 */
public class AgentFrame extends javax.swing.JFrame {

    private MyLib.Agent agent;

    public AgentFrame(MyLib.Agent agent) {
        this.agent = agent;
        initComponents();
        setupUI();
        setSize(1100, 700);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        mainTabs = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();

        // ── Pending Queue tab components ───────────────────────────────────
        jPanel_agentPending = new javax.swing.JPanel();
        jSplitPane_pending = new javax.swing.JSplitPane();
        jScrollPane_agentPending = new javax.swing.JScrollPane();
        agentPendingTable = new javax.swing.JTable();
        jScrollPane_agentDetail = new javax.swing.JScrollPane();
        jPanel_agentDetail = new javax.swing.JPanel();
        jLabel_detTitle = new javax.swing.JLabel();
        jPanel_detailGrid = new javax.swing.JPanel();
        jLabel_pdTxnIdKey = new javax.swing.JLabel();
        pdTxnId = new javax.swing.JLabel();
        jLabel_pdBuyerKey = new javax.swing.JLabel();
        pdBuyer = new javax.swing.JLabel();
        jLabel_pdBlkLotKey = new javax.swing.JLabel();
        pdBlkLot = new javax.swing.JLabel();
        jLabel_pdModelKey = new javax.swing.JLabel();
        pdModel = new javax.swing.JLabel();
        jLabel_pdTCPKey = new javax.swing.JLabel();
        pdTCP = new javax.swing.JLabel();
        jLabel_pdPayMethodKey = new javax.swing.JLabel();
        pdPayMethod = new javax.swing.JLabel();
        jLabel_pdLoanTermKey = new javax.swing.JLabel();
        pdLoanTerm = new javax.swing.JLabel();
        jLabel_pdDiscountKey = new javax.swing.JLabel();
        pdDiscount = new javax.swing.JLabel();
        jPanel_agentActions = new javax.swing.JPanel();
        approveBtn = new javax.swing.JButton();
        rejectBtn = new javax.swing.JButton();

        // ── History tab components ─────────────────────────────────────────
        jPanel_agentHistory = new javax.swing.JPanel();
        jPanel_histToolbar = new javax.swing.JPanel();
        jButton_refreshHistory = new javax.swing.JButton();
        jScrollPane_agentHistory = new javax.swing.JScrollPane();
        agentHistoryTable = new javax.swing.JTable();

        // ── Frame setup ────────────────────────────────────────────────────
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // ── Header panel ───────────────────────────────────────────────────
        jPanel5.setBackground(new java.awt.Color(0, 51, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LUMINA HOMES");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 215, 240));
        jLabel6.setText("Welcome");

        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addComponent(jButton3))
                .addContainerGap())
        );

        mainTabs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        // ── Pending Queue tab ──────────────────────────────────────────────
        jPanel_agentPending.setLayout(new java.awt.BorderLayout());
        jPanel_agentPending.setBackground(new java.awt.Color(248, 249, 252));
        jPanel_agentPending.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));

        agentPendingTable.setModel(new javax.swing.table.DefaultTableModel(
            new String[]{"TXN ID","Buyer","Block","Lot #","Model","Final TCP","Payment","Loan Term","Discount"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        });
        agentPendingTable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        agentPendingTable.setRowHeight(26);
        agentPendingTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        agentPendingTable.setGridColor(new java.awt.Color(220, 220, 220));
        agentPendingTable.setShowGrid(true);
        agentPendingTable.setSelectionBackground(new java.awt.Color(210, 228, 252));
        agentPendingTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 12));
        agentPendingTable.getTableHeader().setBackground(new java.awt.Color(0, 51, 204));
        agentPendingTable.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        agentPendingTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane_agentPending.setViewportView(agentPendingTable);

        // Detail panel (bottom of split)
        jPanel_agentDetail.setLayout(new java.awt.BorderLayout(0, 6));
        jPanel_agentDetail.setBackground(java.awt.Color.WHITE);
        jPanel_agentDetail.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(210, 218, 230)),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)));

        jLabel_detTitle.setText("Transaction Details");
        jLabel_detTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel_detTitle.setForeground(new java.awt.Color(0, 51, 204));

        jPanel_detailGrid.setLayout(new java.awt.GridLayout(0, 2, 8, 4));
        jPanel_detailGrid.setOpaque(false);

        jLabel_pdTxnIdKey.setText("TXN ID:");
        jLabel_pdTxnIdKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pdTxnIdKey.setForeground(new java.awt.Color(80, 80, 80));
        pdTxnId.setText("\u2014");
        pdTxnId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel_pdBuyerKey.setText("Buyer:");
        jLabel_pdBuyerKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pdBuyerKey.setForeground(new java.awt.Color(80, 80, 80));
        pdBuyer.setText("\u2014");
        pdBuyer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel_pdBlkLotKey.setText("Block / Lot:");
        jLabel_pdBlkLotKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pdBlkLotKey.setForeground(new java.awt.Color(80, 80, 80));
        pdBlkLot.setText("\u2014");
        pdBlkLot.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel_pdModelKey.setText("House Model:");
        jLabel_pdModelKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pdModelKey.setForeground(new java.awt.Color(80, 80, 80));
        pdModel.setText("\u2014");
        pdModel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel_pdTCPKey.setText("Final TCP:");
        jLabel_pdTCPKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pdTCPKey.setForeground(new java.awt.Color(80, 80, 80));
        pdTCP.setText("\u2014");
        pdTCP.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel_pdPayMethodKey.setText("Payment Method:");
        jLabel_pdPayMethodKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pdPayMethodKey.setForeground(new java.awt.Color(80, 80, 80));
        pdPayMethod.setText("\u2014");
        pdPayMethod.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel_pdLoanTermKey.setText("Loan Term:");
        jLabel_pdLoanTermKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pdLoanTermKey.setForeground(new java.awt.Color(80, 80, 80));
        pdLoanTerm.setText("\u2014");
        pdLoanTerm.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel_pdDiscountKey.setText("Discount:");
        jLabel_pdDiscountKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pdDiscountKey.setForeground(new java.awt.Color(80, 80, 80));
        pdDiscount.setText("\u2014");
        pdDiscount.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jPanel_detailGrid.add(jLabel_pdTxnIdKey);
        jPanel_detailGrid.add(pdTxnId);
        jPanel_detailGrid.add(jLabel_pdBuyerKey);
        jPanel_detailGrid.add(pdBuyer);
        jPanel_detailGrid.add(jLabel_pdBlkLotKey);
        jPanel_detailGrid.add(pdBlkLot);
        jPanel_detailGrid.add(jLabel_pdModelKey);
        jPanel_detailGrid.add(pdModel);
        jPanel_detailGrid.add(jLabel_pdTCPKey);
        jPanel_detailGrid.add(pdTCP);
        jPanel_detailGrid.add(jLabel_pdPayMethodKey);
        jPanel_detailGrid.add(pdPayMethod);
        jPanel_detailGrid.add(jLabel_pdLoanTermKey);
        jPanel_detailGrid.add(pdLoanTerm);
        jPanel_detailGrid.add(jLabel_pdDiscountKey);
        jPanel_detailGrid.add(pdDiscount);

        approveBtn.setText("Approve");
        approveBtn.setEnabled(false);
        approveBtn.setBackground(new java.awt.Color(34, 120, 34));
        approveBtn.setForeground(java.awt.Color.WHITE);
        approveBtn.setFocusPainted(false);
        approveBtn.setBorderPainted(false);
        approveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        rejectBtn.setText("Reject");
        rejectBtn.setEnabled(false);
        rejectBtn.setBackground(new java.awt.Color(160, 40, 40));
        rejectBtn.setForeground(java.awt.Color.WHITE);
        rejectBtn.setFocusPainted(false);
        rejectBtn.setBorderPainted(false);
        rejectBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel_agentActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 4));
        jPanel_agentActions.setOpaque(false);
        jPanel_agentActions.add(approveBtn);
        jPanel_agentActions.add(rejectBtn);

        jPanel_agentDetail.add(jLabel_detTitle, java.awt.BorderLayout.NORTH);
        jPanel_agentDetail.add(jPanel_detailGrid, java.awt.BorderLayout.CENTER);
        jPanel_agentDetail.add(jPanel_agentActions, java.awt.BorderLayout.SOUTH);

        jScrollPane_agentDetail.setViewportView(jPanel_agentDetail);

        jSplitPane_pending.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane_pending.setResizeWeight(0.60);
        jSplitPane_pending.setDividerSize(5);
        jSplitPane_pending.setBorder(null);
        jSplitPane_pending.setTopComponent(jScrollPane_agentPending);
        jSplitPane_pending.setBottomComponent(jScrollPane_agentDetail);

        jPanel_agentPending.add(jSplitPane_pending, java.awt.BorderLayout.CENTER);

        mainTabs.addTab("Pending Queue", jPanel_agentPending);

        // ── History tab ────────────────────────────────────────────────────
        jPanel_agentHistory.setLayout(new java.awt.BorderLayout(0, 6));
        jPanel_agentHistory.setBackground(new java.awt.Color(248, 249, 252));
        jPanel_agentHistory.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        jButton_refreshHistory.setText("\u27f3  Refresh");
        jButton_refreshHistory.setBackground(new java.awt.Color(0, 51, 204));
        jButton_refreshHistory.setForeground(java.awt.Color.WHITE);
        jButton_refreshHistory.setFocusPainted(false);
        jButton_refreshHistory.setBorderPainted(false);
        jButton_refreshHistory.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jPanel_histToolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 6, 0));
        jPanel_histToolbar.setOpaque(false);
        jPanel_histToolbar.add(jButton_refreshHistory);

        agentHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new String[]{"TXN ID","Buyer","Block","Lot #","Model","Final TCP","Payment","Loan Term","Status","Remark"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        });
        agentHistoryTable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        agentHistoryTable.setRowHeight(26);
        agentHistoryTable.setGridColor(new java.awt.Color(220, 220, 220));
        agentHistoryTable.setShowGrid(true);
        agentHistoryTable.setSelectionBackground(new java.awt.Color(210, 228, 252));
        agentHistoryTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 12));
        agentHistoryTable.getTableHeader().setBackground(new java.awt.Color(0, 51, 204));
        agentHistoryTable.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        agentHistoryTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane_agentHistory.setViewportView(agentHistoryTable);

        jPanel_agentHistory.add(jPanel_histToolbar, java.awt.BorderLayout.NORTH);
        jPanel_agentHistory.add(jScrollPane_agentHistory, java.awt.BorderLayout.CENTER);

        mainTabs.addTab("History", jPanel_agentHistory);

        // ── Status bar (jPanel3) ───────────────────────────────────────────
        jPanel3.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        // ── Outer panel (jPanel1) ──────────────────────────────────────────
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainTabs)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    // ── Non-GEN fields ──────────────────────────────────────────────────────
    private javax.swing.table.DefaultTableModel agentPendingModel;
    private javax.swing.table.DefaultTableModel agentHistoryModel;
    private MyLib.Transaction selectedPendingTxn = null;
    private javax.swing.JLabel statusLabel;

    private static final java.awt.Color BG           = new java.awt.Color(248, 249, 252);
    private static final java.awt.Color HEADER_COLOR = new java.awt.Color(0, 51, 204);

    // ── Setup ──────────────────────────────────────────────────────────────
    private void setupUI() {
        // Status bar label
        jPanel3.setLayout(new java.awt.BorderLayout());
        statusLabel = new javax.swing.JLabel();
        statusLabel.setForeground(java.awt.Color.WHITE);
        statusLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        jPanel3.add(statusLabel, java.awt.BorderLayout.WEST);

        // User labels
        jLabel6.setText(agent.getName() + "  |  Agent");
        statusLabel.setText("  " + agent.getName() + "  |  " + java.time.LocalDate.now());

        // Grab model references from already-constructed tables
        agentPendingModel = (javax.swing.table.DefaultTableModel) agentPendingTable.getModel();
        agentHistoryModel = (javax.swing.table.DefaultTableModel) agentHistoryTable.getModel();

        // Action listeners
        approveBtn.addActionListener(e -> {
            if (selectedPendingTxn == null) return;
            agent.approveTransaction(selectedPendingTxn);
            showMsg("Transaction " + selectedPendingTxn.getTransactionID() + " approved.");
            selectedPendingTxn = null;
            clearPendingDetail();
            approveBtn.setEnabled(false); rejectBtn.setEnabled(false);
            refreshAgentPendingTable(); refreshAgentHistoryTable();
        });

        rejectBtn.addActionListener(e -> {
            if (selectedPendingTxn == null) return;
            javax.swing.JTextArea reasonArea = new javax.swing.JTextArea(4, 30);
            reasonArea.setLineWrap(true); reasonArea.setWrapStyleWord(true);
            int res = javax.swing.JOptionPane.showConfirmDialog(this,
                new javax.swing.JScrollPane(reasonArea), "Enter rejection reason:",
                javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
            if (res == javax.swing.JOptionPane.OK_OPTION) {
                agent.rejectTransaction(selectedPendingTxn,
                    reasonArea.getText().trim().isEmpty() ? "Rejected by agent" : reasonArea.getText().trim());
                showMsg("Transaction " + selectedPendingTxn.getTransactionID() + " rejected.");
                selectedPendingTxn = null;
                clearPendingDetail();
                approveBtn.setEnabled(false); rejectBtn.setEnabled(false);
                refreshAgentPendingTable(); refreshAgentHistoryTable();
            }
        });

        agentPendingTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = agentPendingTable.getSelectedRow();
                java.util.List<MyLib.Transaction> pending = agent.getPendingTransactions();
                if (row >= 0 && row < pending.size()) {
                    selectedPendingTxn = pending.get(row);
                    showPendingDetail(selectedPendingTxn);
                    approveBtn.setEnabled(true); rejectBtn.setEnabled(true);
                } else {
                    selectedPendingTxn = null; clearPendingDetail();
                    approveBtn.setEnabled(false); rejectBtn.setEnabled(false);
                }
            }
        });

        jButton_refreshHistory.addActionListener(e -> refreshAgentHistoryTable());

        // Column widths
        setColWidths(agentPendingTable, 90, 130, 50, 50, 130, 120, 110, 70, 110);
        setColWidths(agentHistoryTable, 90, 130, 50, 50, 130, 120, 110, 70, 85, 140);

        // Initial data
        refreshAgentPendingTable();
        refreshAgentHistoryTable();

    }

    // ── Pending Queue helpers ───────────────────────────────────────────────

    private void refreshAgentPendingTable() {
        if (agentPendingModel == null) return;
        agentPendingModel.setRowCount(0);
        for (MyLib.Transaction t : agent.getPendingTransactions()) {
            MyLib.Lot lot = t.getLot();
            agentPendingModel.addRow(new Object[]{
                t.getTransactionID(),
                t.getBuyer() != null ? t.getBuyer().getName() : "\u2014",
                lot != null ? lot.getBlkNum() : "\u2014",
                lot != null ? lot.getLotNum() : "\u2014",
                lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014",
                "\u20b1" + String.format("%,.2f", t.getFinalTCP()),
                paymentLabel(t.getPaymentMethod()),
                t.getLoanTerm() > 0 ? t.getLoanTerm() + " yr" : "\u2014",
                t.getDiscount() != null ? t.getDiscount().getDiscountDescription() : "None"
            });
        }
    }

    private void showPendingDetail(MyLib.Transaction t) {
        MyLib.Lot lot = t.getLot();
        pdTxnId.setText(t.getTransactionID());
        pdBuyer.setText(t.getBuyer() != null ? t.getBuyer().getName() : "\u2014");
        pdBlkLot.setText(lot != null ? "Block " + lot.getBlkNum() + "  Lot " + lot.getLotNum() : "\u2014");
        pdModel.setText(lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014");
        pdTCP.setText("\u20b1" + String.format("%,.2f", t.getFinalTCP()));
        pdPayMethod.setText(paymentLabel(t.getPaymentMethod()));
        pdLoanTerm.setText(t.getLoanTerm() > 0 ? t.getLoanTerm() + " years" : "\u2014");
        pdDiscount.setText(t.getDiscount() != null ? t.getDiscount().getDiscountDescription() : "None");
    }

    private void clearPendingDetail() {
        for (javax.swing.JLabel lbl : new javax.swing.JLabel[]{
                pdTxnId, pdBuyer, pdBlkLot, pdModel, pdTCP, pdPayMethod, pdLoanTerm, pdDiscount})
            if (lbl != null) lbl.setText("\u2014");
    }

    // ── History helpers ─────────────────────────────────────────────────────

    private void refreshAgentHistoryTable() {
        if (agentHistoryModel == null) return;
        agentHistoryModel.setRowCount(0);
        for (MyLib.Transaction t : agent.getApprovedTransactions()) {
            MyLib.Lot lot = t.getLot();
            agentHistoryModel.addRow(new Object[]{
                t.getTransactionID(),
                t.getBuyer() != null ? t.getBuyer().getName() : "\u2014",
                lot != null ? lot.getBlkNum() : "\u2014",
                lot != null ? lot.getLotNum() : "\u2014",
                lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014",
                "\u20b1" + String.format("%,.2f", t.getFinalTCP()),
                paymentLabel(t.getPaymentMethod()),
                t.getLoanTerm() > 0 ? t.getLoanTerm() + " yr" : "\u2014",
                t.getTransactionStatus(),
                t.getRemark() != null && !t.getRemark().isEmpty() ? t.getRemark() : "\u2014"
            });
        }
    }

    // ── Shared helpers ──────────────────────────────────────────────────────

    private void setColWidths(javax.swing.JTable t, int... widths) {
        for (int i = 0; i < widths.length && i < t.getColumnCount(); i++)
            t.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
    }

    private String paymentLabel(MyLib.PaymentMethod pm) {
        if (pm == null)                  return "\u2014";
        if (pm instanceof MyLib.Cash)    return "Cash";
        if (pm instanceof MyLib.Bank)    return "Bank Financing";
        if (pm instanceof MyLib.Pagibig) return "Pag-IBIG";
        if (pm instanceof MyLib.EMI)     return "EMI (In-House)";
        return pm.getClass().getSimpleName();
    }

    private void showMsg(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable agentHistoryTable;
    private javax.swing.JTable agentPendingTable;
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_refreshHistory;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_detTitle;
    private javax.swing.JLabel jLabel_pdBlkLotKey;
    private javax.swing.JLabel jLabel_pdBuyerKey;
    private javax.swing.JLabel jLabel_pdDiscountKey;
    private javax.swing.JLabel jLabel_pdLoanTermKey;
    private javax.swing.JLabel jLabel_pdModelKey;
    private javax.swing.JLabel jLabel_pdPayMethodKey;
    private javax.swing.JLabel jLabel_pdTCPKey;
    private javax.swing.JLabel jLabel_pdTxnIdKey;
    private javax.swing.JTabbedPane mainTabs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_agentActions;
    private javax.swing.JPanel jPanel_agentDetail;
    private javax.swing.JPanel jPanel_agentHistory;
    private javax.swing.JPanel jPanel_agentPending;
    private javax.swing.JPanel jPanel_detailGrid;
    private javax.swing.JPanel jPanel_histToolbar;
    private javax.swing.JLabel pdBlkLot;
    private javax.swing.JLabel pdBuyer;
    private javax.swing.JLabel pdDiscount;
    private javax.swing.JLabel pdLoanTerm;
    private javax.swing.JLabel pdModel;
    private javax.swing.JLabel pdPayMethod;
    private javax.swing.JLabel pdTCP;
    private javax.swing.JLabel pdTxnId;
    private javax.swing.JButton rejectBtn;
    private javax.swing.JScrollPane jScrollPane_agentDetail;
    private javax.swing.JScrollPane jScrollPane_agentHistory;
    private javax.swing.JScrollPane jScrollPane_agentPending;
    private javax.swing.JSplitPane jSplitPane_pending;
    // End of variables declaration//GEN-END:variables
}
