/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;

/**
 * Role-specific screen for Buyer users.
 * Tabs: Browse | Purchase | My Transactions
 *
 * @author Group 1
 */
public class BuyerFrame extends javax.swing.JFrame {

    private MyLib.Buyer buyer;

    public BuyerFrame(MyLib.Buyer buyer) {
        this.buyer = buyer;
        initComponents();
        setupUI();
        setSize(1100, 700);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        mainTabs = new javax.swing.JTabbedPane();
        jPanel_browse = new javax.swing.JPanel();
        jPanel_browseFilter = new javax.swing.JPanel();
        jLabel_maxBudget = new javax.swing.JLabel();
        buyerBudgetField = new javax.swing.JTextField();
        jLabel_blockFilter = new javax.swing.JLabel();
        buyerBlockCombo = new javax.swing.JComboBox();
        jLabel_floorAreaFilter = new javax.swing.JLabel();
        jTextField_floorArea = new javax.swing.JTextField();
        jLabel_lotAreaFilter = new javax.swing.JLabel();
        jTextField_lotArea = new javax.swing.JTextField();
        jButton_applyFilter = new javax.swing.JButton();
        jButton_showAll = new javax.swing.JButton();
        jScrollPane_browse = new javax.swing.JScrollPane();
        browseLotTable = new javax.swing.JTable();
        jPanel_browseSouth = new javax.swing.JPanel();
        jButton_selectLot = new javax.swing.JButton();
        jPanel_purchase = new javax.swing.JPanel();
        jSplitPane_purchase = new javax.swing.JSplitPane();
        jScrollPane_purchaseLeft = new javax.swing.JScrollPane();
        jPanel_purchaseLeft = new javax.swing.JPanel();
        jLabel_selLotHeader = new javax.swing.JLabel();
        jLabel_blk = new javax.swing.JLabel();
        jComboBox_selBlock = new javax.swing.JComboBox();
        jLabel_lot = new javax.swing.JLabel();
        jComboBox_selLot = new javax.swing.JComboBox();
        jLabel_discHeader = new javax.swing.JLabel();
        jCheckBox_senior = new javax.swing.JCheckBox();
        jCheckBox_pwd = new javax.swing.JCheckBox();
        jCheckBox_firstTime = new javax.swing.JCheckBox();
        jCheckBox_veteran = new javax.swing.JCheckBox();
        jLabel_payHeader = new javax.swing.JLabel();
        jLabel_payMethod = new javax.swing.JLabel();
        jComboBox_payMethod = new javax.swing.JComboBox();
        jLabel_loanTerm = new javax.swing.JLabel();
        jComboBox_loanTerm = new javax.swing.JComboBox();
        jButton_reserve = new javax.swing.JButton();
        jButton_submitToAgent = new javax.swing.JButton();
        jPanel_purchaseDetail = new javax.swing.JPanel();
        jLabel_modelName = new javax.swing.JLabel();
        jPanel_detailGrid = new javax.swing.JPanel();
        jLabel_tcpKey = new javax.swing.JLabel();
        jLabel_tcp = new javax.swing.JLabel();
        jLabel_discAmtKey = new javax.swing.JLabel();
        jLabel_discountAmt = new javax.swing.JLabel();
        jLabel_finalTcpKey = new javax.swing.JLabel();
        jLabel_finalTcp = new javax.swing.JLabel();
        jLabel_resFeeKey = new javax.swing.JLabel();
        jLabel_resFee = new javax.swing.JLabel();
        jLabel_downPayKey = new javax.swing.JLabel();
        jLabel_downPayment = new javax.swing.JLabel();
        jLabel_dpTargetKey = new javax.swing.JLabel();
        jLabel_dpTarget = new javax.swing.JLabel();
        jLabel_dpPeriodKey = new javax.swing.JLabel();
        jLabel_dpPeriod = new javax.swing.JLabel();
        jLabel_interestKey = new javax.swing.JLabel();
        jLabel_interestRate = new javax.swing.JLabel();
        jLabel_monthlyKey = new javax.swing.JLabel();
        jLabel_monthlyAmort = new javax.swing.JLabel();
        jScrollPane_amort = new javax.swing.JScrollPane();
        jTable_amortTable = new javax.swing.JTable();
        jPanel_myTxns = new javax.swing.JPanel();
        jPanel_txnToolbar = new javax.swing.JPanel();
        jButton_refreshTxns = new javax.swing.JButton();
        jScrollPane_buyerTxns = new javax.swing.JScrollPane();
        buyerTxnTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 51, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LUMINA HOMES");

        jLabel6.setForeground(new java.awt.Color(190, 215, 240));
        jLabel6.setText("Welcome");

        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addComponent(jButton3))
                .addContainerGap())
        );

        mainTabs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jPanel_browse.setBackground(new java.awt.Color(248, 249, 252));
        jPanel_browse.setLayout(new java.awt.BorderLayout());

        jPanel_browseFilter.setBackground(new java.awt.Color(235, 240, 248));
        jPanel_browseFilter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel_maxBudget.setText("Max Budget (₱):");
        jPanel_browseFilter.add(jLabel_maxBudget);

        buyerBudgetField.setColumns(8);
        jPanel_browseFilter.add(buyerBudgetField);

        jLabel_blockFilter.setText("Block:");
        jPanel_browseFilter.add(jLabel_blockFilter);

        buyerBlockCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "1", "2", "3", "4", "5" }));
        jPanel_browseFilter.add(buyerBlockCombo);

        jLabel_floorAreaFilter.setText("Floor Area ≥ sqm:");
        jPanel_browseFilter.add(jLabel_floorAreaFilter);

        jTextField_floorArea.setColumns(5);
        jPanel_browseFilter.add(jTextField_floorArea);

        jLabel_lotAreaFilter.setText("Lot Area ≥ sqm:");
        jPanel_browseFilter.add(jLabel_lotAreaFilter);

        jTextField_lotArea.setColumns(5);
        jPanel_browseFilter.add(jTextField_lotArea);

        jButton_applyFilter.setText("Apply Filters");
        jPanel_browseFilter.add(jButton_applyFilter);

        jButton_showAll.setText("Show All");
        jPanel_browseFilter.add(jButton_showAll);

        jPanel_browse.add(jPanel_browseFilter, java.awt.BorderLayout.NORTH);

        browseLotTable.setRowHeight(26);
        jScrollPane_browse.setViewportView(browseLotTable);

        jPanel_browse.add(jScrollPane_browse, java.awt.BorderLayout.CENTER);

        jPanel_browseSouth.setOpaque(false);
        jPanel_browseSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton_selectLot.setText("Select Lot → Go to Purchase");
        jPanel_browseSouth.add(jButton_selectLot);

        jPanel_browse.add(jPanel_browseSouth, java.awt.BorderLayout.SOUTH);

        mainTabs.addTab("Browse", jPanel_browse);

        jPanel_purchase.setBackground(new java.awt.Color(248, 249, 252));
        jPanel_purchase.setLayout(new java.awt.BorderLayout());

        jSplitPane_purchase.setDividerLocation(300);
        jSplitPane_purchase.setDividerSize(4);
        jSplitPane_purchase.setResizeWeight(0.28);

        jPanel_purchaseLeft.setBackground(new java.awt.Color(248, 249, 252));

        jLabel_selLotHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel_selLotHeader.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_selLotHeader.setText("Select a Lot");

        jLabel_blk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_blk.setText("Block:");

        jComboBox_selBlock.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "—", "1", "2", "3", "4", "5" }));

        jLabel_lot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_lot.setText("Lot:");

        jComboBox_selLot.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel_discHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel_discHeader.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_discHeader.setText("Discount");

        jCheckBox_senior.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox_senior.setText("Senior Citizen — 20%");

        jCheckBox_pwd.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox_pwd.setText("PWD — 20%");

        jCheckBox_firstTime.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox_firstTime.setText("First Time Buyer — 5%");

        jCheckBox_veteran.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox_veteran.setText("Veteran — 10%");

        jLabel_payHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel_payHeader.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_payHeader.setText("Payment Options");

        jLabel_payMethod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_payMethod.setText("Payment Method:");

        jComboBox_payMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Bank", "Pag-IBIG", "EMI (In-House)" }));

        jLabel_loanTerm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_loanTerm.setText("Loan Term (yrs):");

        jComboBox_loanTerm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "15", "20", "25", "30" }));

        jButton_reserve.setBackground(new java.awt.Color(0, 120, 60));
        jButton_reserve.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton_reserve.setForeground(new java.awt.Color(255, 255, 255));
        jButton_reserve.setText("Reserve Lot");
        jButton_reserve.setEnabled(false);
        jButton_reserve.setBorderPainted(false);
        jButton_reserve.setFocusPainted(false);

        jButton_submitToAgent.setBackground(new java.awt.Color(0, 51, 204));
        jButton_submitToAgent.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton_submitToAgent.setForeground(new java.awt.Color(255, 255, 255));
        jButton_submitToAgent.setText("Forward to Agent \u2014 Buy");
        jButton_submitToAgent.setEnabled(false);
        jButton_submitToAgent.setBorderPainted(false);
        jButton_submitToAgent.setFocusPainted(false);

        javax.swing.GroupLayout jPanel_purchaseLeftLayout = new javax.swing.GroupLayout(jPanel_purchaseLeft);
        jPanel_purchaseLeft.setLayout(jPanel_purchaseLeftLayout);
        jPanel_purchaseLeftLayout.setHorizontalGroup(
            jPanel_purchaseLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_selLotHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_purchaseLeftLayout.createSequentialGroup()
                .addComponent(jLabel_blk, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_selBlock, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_purchaseLeftLayout.createSequentialGroup()
                .addComponent(jLabel_lot, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_selLot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel_discHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCheckBox_senior)
            .addComponent(jCheckBox_pwd)
            .addComponent(jCheckBox_firstTime)
            .addComponent(jCheckBox_veteran)
            .addComponent(jLabel_payHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_purchaseLeftLayout.createSequentialGroup()
                .addComponent(jLabel_payMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_payMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_purchaseLeftLayout.createSequentialGroup()
                .addComponent(jLabel_loanTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_loanTerm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jButton_reserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_submitToAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_purchaseLeftLayout.setVerticalGroup(
            jPanel_purchaseLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_purchaseLeftLayout.createSequentialGroup()
                .addComponent(jLabel_selLotHeader)
                .addGap(8, 8, 8)
                .addGroup(jPanel_purchaseLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_blk, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_selBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel_purchaseLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_lot, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_selLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel_discHeader)
                .addGap(8, 8, 8)
                .addComponent(jCheckBox_senior)
                .addGap(2, 2, 2)
                .addComponent(jCheckBox_pwd)
                .addGap(2, 2, 2)
                .addComponent(jCheckBox_firstTime)
                .addGap(2, 2, 2)
                .addComponent(jCheckBox_veteran)
                .addGap(16, 16, 16)
                .addComponent(jLabel_payHeader)
                .addGap(8, 8, 8)
                .addGroup(jPanel_purchaseLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_payMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_payMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel_purchaseLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_loanTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_loanTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButton_reserve)
                .addGap(4, 4, 4)
                .addComponent(jButton_submitToAgent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane_purchaseLeft.setViewportView(jPanel_purchaseLeft);

        jSplitPane_purchase.setLeftComponent(jScrollPane_purchaseLeft);

        jPanel_purchaseDetail.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_purchaseDetail.setLayout(new java.awt.BorderLayout());

        jLabel_modelName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel_modelName.setForeground(new java.awt.Color(128, 128, 128));
        jLabel_modelName.setText("Select a block and lot to see details");
        jPanel_purchaseDetail.add(jLabel_modelName, java.awt.BorderLayout.NORTH);

        jPanel_detailGrid.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_detailGrid.setLayout(new java.awt.GridLayout(0, 2));

        jLabel_tcpKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_tcpKey.setText("TCP:");
        jPanel_detailGrid.add(jLabel_tcpKey);

        jLabel_tcp.setText("—");
        jPanel_detailGrid.add(jLabel_tcp);

        jLabel_discAmtKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_discAmtKey.setText("Discount:");
        jPanel_detailGrid.add(jLabel_discAmtKey);

        jLabel_discountAmt.setText("—");
        jPanel_detailGrid.add(jLabel_discountAmt);

        jLabel_finalTcpKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_finalTcpKey.setText("Final TCP:");
        jPanel_detailGrid.add(jLabel_finalTcpKey);

        jLabel_finalTcp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_finalTcp.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_finalTcp.setText("—");
        jPanel_detailGrid.add(jLabel_finalTcp);

        jLabel_resFeeKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_resFeeKey.setText("Reservation Fee:");
        jPanel_detailGrid.add(jLabel_resFeeKey);

        jLabel_resFee.setText("—");
        jPanel_detailGrid.add(jLabel_resFee);

        jLabel_downPayKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_downPayKey.setText("Down Payment:");
        jPanel_detailGrid.add(jLabel_downPayKey);

        jLabel_downPayment.setText("—");
        jPanel_detailGrid.add(jLabel_downPayment);

        jLabel_dpTargetKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_dpTargetKey.setText("DP Monthly Target:");
        jPanel_detailGrid.add(jLabel_dpTargetKey);

        jLabel_dpTarget.setText("—");
        jPanel_detailGrid.add(jLabel_dpTarget);

        jLabel_dpPeriodKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_dpPeriodKey.setText("DP Period:");
        jPanel_detailGrid.add(jLabel_dpPeriodKey);

        jLabel_dpPeriod.setText("—");
        jPanel_detailGrid.add(jLabel_dpPeriod);

        jLabel_interestKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_interestKey.setText("Interest Rate:");
        jPanel_detailGrid.add(jLabel_interestKey);

        jLabel_interestRate.setText("—");
        jPanel_detailGrid.add(jLabel_interestRate);

        jLabel_monthlyKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_monthlyKey.setText("Monthly Amortization:");
        jPanel_detailGrid.add(jLabel_monthlyKey);

        jLabel_monthlyAmort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_monthlyAmort.setForeground(new java.awt.Color(0, 120, 0));
        jLabel_monthlyAmort.setText("—");
        jPanel_detailGrid.add(jLabel_monthlyAmort);

        jPanel_purchaseDetail.add(jPanel_detailGrid, java.awt.BorderLayout.CENTER);

        jTable_amortTable.setRowHeight(26);
        jScrollPane_amort.setViewportView(jTable_amortTable);

        jPanel_purchaseDetail.add(jScrollPane_amort, java.awt.BorderLayout.SOUTH);

        jSplitPane_purchase.setRightComponent(jPanel_purchaseDetail);

        jPanel_purchase.add(jSplitPane_purchase, java.awt.BorderLayout.CENTER);

        mainTabs.addTab("Purchase", jPanel_purchase);

        jPanel_myTxns.setBackground(new java.awt.Color(248, 249, 252));
        jPanel_myTxns.setLayout(new java.awt.BorderLayout());

        jPanel_txnToolbar.setOpaque(false);
        jPanel_txnToolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton_refreshTxns.setText("⟳  Refresh");
        jPanel_txnToolbar.add(jButton_refreshTxns);

        jPanel_myTxns.add(jPanel_txnToolbar, java.awt.BorderLayout.NORTH);

        buyerTxnTable.setRowHeight(26);
        jScrollPane_buyerTxns.setViewportView(buyerTxnTable);

        jPanel_myTxns.add(jScrollPane_buyerTxns, java.awt.BorderLayout.CENTER);

        mainTabs.addTab("My Transactions", jPanel_myTxns);

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainTabs)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    // ── Non-GEN fields ──────────────────────────────────────────────────────
    private java.util.List<MyLib.Lot> buyerCurrentLots = new java.util.ArrayList<>();
    private javax.swing.JLabel statusLabel;

    private static final java.awt.Color BG           = new java.awt.Color(248, 249, 252);
    private static final java.awt.Color HEADER_COLOR = new java.awt.Color(0, 51, 204);

    // ── Setup ──────────────────────────────────────────────────────────────
    private void setupUI() {
        // Status bar
        jPanel3.setLayout(new java.awt.BorderLayout());
        statusLabel = new javax.swing.JLabel();
        statusLabel.setForeground(java.awt.Color.WHITE);
        statusLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        jPanel3.add(statusLabel, java.awt.BorderLayout.WEST);

        // User label
        jLabel6.setText(buyer.getName() + "  |  Buyer");
        statusLabel.setText("  " + buyer.getName() + "  |  " + java.time.LocalDate.now());

        // Build table models with columns and attach to tables (AgentFrame pattern)
        browseLotTable.setModel(new javax.swing.table.DefaultTableModel(
            new String[]{"Block","Lot #","House Model","Total Contract Price","Floor Area","Lot Area","Phase","Status"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        });

        javax.swing.table.DefaultTableModel amortModel = new javax.swing.table.DefaultTableModel(
            new String[]{"Loan Term","Monthly Payment (\u20b1)"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        for (int yr : new int[]{5, 10, 15, 20, 25, 30})
            amortModel.addRow(new Object[]{yr + " years", "\u2014 "});
        jTable_amortTable.setModel(amortModel);

        buyerTxnTable.setModel(new javax.swing.table.DefaultTableModel(
            new String[]{"TXN ID","Block","Lot #","Model","Final TCP","Payment","Loan Term","Status","Reserved Until","Agent","Remark"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        });

        // Action listeners
        jButton_applyFilter.addActionListener(e -> applyBuyerFilter());
        jButton_showAll.addActionListener(e -> {
            buyerBudgetField.setText("");
            buyerBlockCombo.setSelectedIndex(0);
            jTextField_floorArea.setText("");
            jTextField_lotArea.setText("");
            populateBrowseTable(buyer.viewAvailableLots());
        });
        jButton_selectLot.addActionListener(e -> {
            int row = browseLotTable.getSelectedRow();
            if (row < 0) { showMsg("Please select a lot first."); return; }
            MyLib.Lot lot = buyerCurrentLots.get(row);
            jComboBox_selBlock.setSelectedItem(String.valueOf(lot.getBlkNum()));
            jComboBox_selLot.setSelectedItem(String.valueOf(lot.getLotNum()));
            mainTabs.setSelectedIndex(1);
        });
        jComboBox_selBlock.addActionListener(e -> refreshPurchaseDetails());
        jComboBox_selLot.addActionListener(e -> refreshPurchaseDetails());
        jComboBox_loanTerm.addActionListener(e -> refreshPurchaseDetails());
        jComboBox_payMethod.addActionListener(e -> onPayMethodChanged());

        java.awt.event.ItemListener discListener = evt -> {
            if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                javax.swing.JCheckBox src = (javax.swing.JCheckBox) evt.getSource();
                if (src != jCheckBox_senior)    jCheckBox_senior.setSelected(false);
                if (src != jCheckBox_pwd)       jCheckBox_pwd.setSelected(false);
                if (src != jCheckBox_firstTime) jCheckBox_firstTime.setSelected(false);
                if (src != jCheckBox_veteran)   jCheckBox_veteran.setSelected(false);
            }
            refreshPurchaseDetails();
        };
        jCheckBox_senior.addItemListener(discListener);
        jCheckBox_pwd.addItemListener(discListener);
        jCheckBox_firstTime.addItemListener(discListener);
        jCheckBox_veteran.addItemListener(discListener);
        jButton_reserve.addActionListener(e -> reserveLot());
        jButton_submitToAgent.addActionListener(e -> submitPurchaseToAgent());
        jButton_refreshTxns.addActionListener(e -> refreshBuyerTxnTable());

        // Table styling and column widths
        styleTable(browseLotTable);
        setColWidths(browseLotTable, 55, 55, 150, 160, 90, 80, 80, 90);
        styleTable(jTable_amortTable);
        setColWidths(jTable_amortTable, 130, 200);
        jTable_amortTable.setPreferredScrollableViewportSize(new java.awt.Dimension(330, 195));
        styleTable(buyerTxnTable);
        setColWidths(buyerTxnTable, 100, 50, 50, 140, 140, 110, 70, 85, 110, 120, 140);
        buyerTxnTable.setDefaultRenderer(Object.class, statusColorRenderer(7));

        // Auto-select discount checkbox based on buyer's BuyerType
        switch (buyer.getBuyerType()) {
            case SENIOR_CITIZEN:   jCheckBox_senior.setSelected(true);    break;
            case PWD:              jCheckBox_pwd.setSelected(true);        break;
            case FIRST_TIME_BUYER: jCheckBox_firstTime.setSelected(true); break;
            case VETERAN:          jCheckBox_veteran.setSelected(true);    break;
            default: break; // REGULAR: no discount
        }

        // Initial data
        populateBrowseTable(buyer.viewAvailableLots());
        refreshBuyerTxnTable();

        // Set initial payment method visibility (Cash is default — hide loan term & amort)
        onPayMethodChanged();
    }

    // ── Browse helpers ──────────────────────────────────────────────────────

    private void applyBuyerFilter() {
        double maxBudget = parseSafe(buyerBudgetField.getText(), 0);
        double minFloor  = parseSafe(jTextField_floorArea.getText(), 0);
        double minLot    = parseSafe(jTextField_lotArea.getText(), 0);
        String sel       = (String) buyerBlockCombo.getSelectedItem();
        int    blockNum  = "All".equals(sel) ? 0 : Integer.parseInt(sel);

        AppContext ctx = AppContext.getInstance();
        java.util.List<MyLib.Lot> result = buyer.viewAvailableLots();

        if (maxBudget > 0) {
            java.util.List<MyLib.PropertyUnit> affordable = ctx.getCatalog().getUnitsByBudget(maxBudget);
            java.util.List<MyLib.Lot> filtered = new java.util.ArrayList<>();
            for (MyLib.Lot l : result)
                if (l.getHouseModel() != null && affordable.contains(l.getHouseModel())) filtered.add(l);
            result = filtered;
        }
        if (blockNum > 0) {
            java.util.List<MyLib.Lot> filtered = new java.util.ArrayList<>();
            for (MyLib.Lot l : result) if (l.getBlkNum() == blockNum) filtered.add(l);
            result = filtered;
        }
        if (minFloor > 0) {
            java.util.List<MyLib.Lot> filtered = new java.util.ArrayList<>();
            for (MyLib.Lot l : result)
                if (l.getHouseModel() != null && l.getHouseModel().getFloorArea() >= minFloor) filtered.add(l);
            result = filtered;
        }
        if (minLot > 0) {
            java.util.List<MyLib.Lot> filtered = new java.util.ArrayList<>();
            for (MyLib.Lot l : result)
                if (l.getHouseModel() != null && l.getHouseModel().getLotArea() >= minLot) filtered.add(l);
            result = filtered;
        }
        populateBrowseTable(result);
    }

    private void populateBrowseTable(java.util.List<MyLib.Lot> lots) {
        buyerCurrentLots = lots;
        javax.swing.table.DefaultTableModel m = (javax.swing.table.DefaultTableModel) browseLotTable.getModel();
        m.setRowCount(0);
        for (MyLib.Lot lot : lots) {
            MyLib.PropertyUnit u = lot.getHouseModel();
            m.addRow(new Object[]{
                lot.getBlkNum(), lot.getLotNum(),
                u != null ? u.getModelName() : "\u2014",
                u != null ? "\u20b1" + String.format("%,.0f", u.getEstimatedTCP()) : "\u2014",
                u != null ? u.getFloorArea() + " sqm" : "\u2014",
                u != null ? u.getLotArea()   + " sqm" : "\u2014",
                u != null ? u.getPhase() : "\u2014",
                lot.getTransactionStatus()
            });
        }
    }

    // ── Purchase helpers ────────────────────────────────────────────────────

    private void refreshPurchaseDetails() {
        String blkSel = (String) jComboBox_selBlock.getSelectedItem();
        if ("\u2014".equals(blkSel)) {
            clearPurchaseDetails();
            jButton_reserve.setEnabled(false);
            jButton_submitToAgent.setEnabled(false);
            return;
        }
        int blk    = Integer.parseInt(blkSel);
        int lotNum = Integer.parseInt((String) jComboBox_selLot.getSelectedItem());
        MyLib.Lot lot = AppContext.getInstance().getSubdivision().findLot(blk, lotNum);
        if (lot == null || !lot.getAvailability()) {
            clearPurchaseDetails();
            jLabel_modelName.setText("Block " + blk + " Lot " + lotNum
                + (lot != null ? " \u2014 not available (" + lot.getTransactionStatus() + ")" : " \u2014 not found"));
            jLabel_modelName.setForeground(new java.awt.Color(180, 0, 0));
            jButton_reserve.setEnabled(false);
            jButton_submitToAgent.setEnabled(false);
            return;
        }
        MyLib.PropertyUnit u = lot.getHouseModel();
        if (u == null) {
            clearPurchaseDetails();
            jLabel_modelName.setText("Block " + blk + " Lot " + lotNum + " \u2014 no model assigned");
            jLabel_modelName.setForeground(java.awt.Color.GRAY);
            jButton_reserve.setEnabled(false);
            jButton_submitToAgent.setEnabled(false);
            return;
        }

        jLabel_modelName.setText(u.getModelName() + "  (Block " + blk + " \u00b7 Lot " + lotNum + ")");
        jLabel_modelName.setForeground(HEADER_COLOR);

        double tcp      = u.getEstimatedTCP();
        MyLib.Discount disc = buildPurchaseDiscount();
        double discAmt  = disc != null ? disc.computeDiscount(tcp) : 0;
        double finalTcp = tcp - discAmt;

        jLabel_tcp.setText("\u20b1" + String.format("%,.2f", tcp));
        jLabel_discountAmt.setText(disc != null
            ? "\u20b1" + String.format("%,.2f", discAmt) + " (" + disc.getDiscountDescription() + ")"
            : "None");
        jLabel_finalTcp.setText("\u20b1" + String.format("%,.2f", finalTcp));
        jLabel_resFee.setText("\u20b1" + String.format("%,.2f", u.getReservationFee()));
        jLabel_downPayment.setText("\u20b1" + String.format("%,.2f", u.getDownPayment()));
        jLabel_dpTarget.setText("\u20b1" + String.format("%,.2f", u.getDpTarget()) + " / month");
        jLabel_dpPeriod.setText((int) u.getDpPeriod() + " months");

        String payMethod = (String) jComboBox_payMethod.getSelectedItem();
        boolean isCash   = "Cash".equals(payMethod);

        jLabel_loanTerm.setVisible(!isCash);
        jComboBox_loanTerm.setVisible(!isCash);
        jScrollPane_amort.setVisible(!isCash);

        if (isCash) {
            jLabel_interestRate.setText("N/A \u2014 Full Cash Payment");
            jLabel_monthlyAmort.setText("Full Payment: \u20b1" + String.format("%,.2f", finalTcp));
        } else {
            if (jComboBox_loanTerm.getSelectedItem() == null) {
                jButton_reserve.setEnabled(true);
                jButton_submitToAgent.setEnabled(true);
                return;
            }
            double rate  = getEffectiveRate(u, payMethod);
            int    term  = (Integer) jComboBox_loanTerm.getSelectedItem();
            jLabel_interestRate.setText(String.format("%.2f%% p.a. (%s)", rate * 100, payMethod));
            double monthly = computeMonthlyAmort(u.getLoanableAmount(), term, rate);
            jLabel_monthlyAmort.setText("\u20b1" + String.format("%,.2f", monthly) + " / month");

            javax.swing.table.DefaultTableModel am = (javax.swing.table.DefaultTableModel) jTable_amortTable.getModel();
            am.setRowCount(0);
            int[] terms = getTermsForMethod(payMethod);
            for (int yr : terms)
                am.addRow(new Object[]{yr + " years", "\u20b1" + String.format("%,.2f", computeMonthlyAmort(u.getLoanableAmount(), yr, rate))});
            for (int i = 0; i < terms.length; i++)
                if (terms[i] == term) { jTable_amortTable.setRowSelectionInterval(i, i); break; }
        }

        jButton_reserve.setEnabled(true);
        jButton_submitToAgent.setEnabled(true);
    }

    private void onPayMethodChanged() {
        String method = (String) jComboBox_payMethod.getSelectedItem();
        if (!"Cash".equals(method)) {
            int[] terms = getTermsForMethod(method);
            java.awt.event.ActionListener[] als = jComboBox_loanTerm.getActionListeners();
            for (java.awt.event.ActionListener l : als) jComboBox_loanTerm.removeActionListener(l);
            jComboBox_loanTerm.removeAllItems();
            for (int yr : terms) jComboBox_loanTerm.addItem(yr);
            for (java.awt.event.ActionListener l : als) jComboBox_loanTerm.addActionListener(l);
        }
        boolean isCash = "Cash".equals(method);
        jLabel_loanTerm.setVisible(!isCash);
        jComboBox_loanTerm.setVisible(!isCash);
        jScrollPane_amort.setVisible(!isCash);
        refreshPurchaseDetails();
    }

    private double getEffectiveRate(MyLib.PropertyUnit u, String payMethod) {
        switch (payMethod) {
            case "Bank":           return 0.065;    // 6.50% p.a.
            case "Pag-IBIG":
                return "Aimee Inner".equals(u.getModelName()) ? 0.03 : 0.0625; // 3% socialized / 6.25% standard
            case "EMI (In-House)": return 0.14;     // 14% p.a.
            default:               return 0.0;
        }
    }

    private int[] getTermsForMethod(String payMethod) {
        switch (payMethod) {
            case "EMI (In-House)": return new int[]{5, 10, 15};
            case "Bank":           return new int[]{5, 10, 15, 20};
            default:               return new int[]{5, 10, 15, 20, 25, 30}; // Pag-IBIG
        }
    }

    private double computeMonthlyAmort(double loanable, int years, double annualRate) {
        double r = annualRate / 12.0;
        int    n = years * 12;
        if (r == 0 || n == 0) return 0;
        return loanable * (r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1);
    }

    private void clearPurchaseDetails() {
        jLabel_modelName.setText("Select a block and lot to see details");
        jLabel_modelName.setForeground(java.awt.Color.GRAY);
        for (javax.swing.JLabel lbl : new javax.swing.JLabel[]{
                jLabel_tcp, jLabel_discountAmt, jLabel_finalTcp, jLabel_resFee,
                jLabel_downPayment, jLabel_dpTarget, jLabel_dpPeriod,
                jLabel_interestRate, jLabel_monthlyAmort})
            lbl.setText("\u2014");
        javax.swing.table.DefaultTableModel am = (javax.swing.table.DefaultTableModel) jTable_amortTable.getModel();
        am.setRowCount(0);
        for (int yr : new int[]{5, 10, 15, 20, 25, 30})
            am.addRow(new Object[]{yr + " years", "\u2014 "});
        // Sync loan-term / amort visibility with current payment method
        boolean isCash = "Cash".equals(jComboBox_payMethod.getSelectedItem());
        jLabel_loanTerm.setVisible(!isCash);
        jComboBox_loanTerm.setVisible(!isCash);
        jScrollPane_amort.setVisible(!isCash);
    }

    private MyLib.Discount buildPurchaseDiscount() {
        if (jCheckBox_senior.isSelected())    return new MyLib.SeniorCitizenDiscount();
        if (jCheckBox_pwd.isSelected())       return new MyLib.PWDDiscount();
        if (jCheckBox_firstTime.isSelected()) return new MyLib.FirstTimeDiscount();
        if (jCheckBox_veteran.isSelected())   return new MyLib.VeteranDiscount();
        return null;
    }

    private void submitPurchaseToAgent() {
        String blkSel = (String) jComboBox_selBlock.getSelectedItem();
        if ("\u2014".equals(blkSel)) return;
        int blk    = Integer.parseInt(blkSel);
        int lotNum = Integer.parseInt((String) jComboBox_selLot.getSelectedItem());
        AppContext ctx = AppContext.getInstance();
        MyLib.Lot lot = ctx.getSubdivision().findLot(blk, lotNum);
        if (lot == null || !lot.getAvailability()) {
            showMsg("This lot is no longer available."); refreshPurchaseDetails(); return;
        }
        java.util.List<MyLib.Agent> agents = ctx.getAgents();
        if (agents.isEmpty()) { showMsg("No agents available."); return; }

        boolean isCash = "Cash".equals(jComboBox_payMethod.getSelectedItem());
        MyLib.Agent assignedAgent = agents.get(0);
        int loanTerm = (isCash || jComboBox_loanTerm.getSelectedItem() == null) ? 0
                     : (Integer) jComboBox_loanTerm.getSelectedItem();
        MyLib.Discount disc    = buildPurchaseDiscount();
        MyLib.PaymentMethod pm = buildPurchasePaymentMethod(loanTerm, lot);

        MyLib.Transaction txn = new MyLib.Transaction(buyer, lot, pm, disc);
        txn.setTransactionType("BUY");
        txn.setTransactionStatus(MyLib.Status.PENDING);
        txn.setAssignedAgent(assignedAgent);
        txn.setLoanTerm(loanTerm);

        lot.updateStatus(MyLib.Status.SUBMITTED);
        buyer.addTransaction(txn);
        assignedAgent.addPendingTransaction(txn);
        ctx.addTransaction(txn);

        showMsg("Submitted! Transaction #" + txn.getTransactionID()
            + " forwarded to " + assignedAgent.getName() + ".");

        jComboBox_selBlock.setSelectedIndex(0);
        jCheckBox_senior.setSelected(false);
        jCheckBox_pwd.setSelected(false);
        jCheckBox_firstTime.setSelected(false);
        jCheckBox_veteran.setSelected(false);
        populateBrowseTable(buyer.viewAvailableLots());
        refreshBuyerTxnTable();
        mainTabs.setSelectedIndex(2);
    }

    private void reserveLot() {
        String blkSel = (String) jComboBox_selBlock.getSelectedItem();
        if ("\u2014".equals(blkSel)) return;
        int blk    = Integer.parseInt(blkSel);
        int lotNum = Integer.parseInt((String) jComboBox_selLot.getSelectedItem());
        AppContext ctx = AppContext.getInstance();
        MyLib.Lot lot = ctx.getSubdivision().findLot(blk, lotNum);
        if (lot == null || !lot.getAvailability()) {
            showMsg("This lot is no longer available."); refreshPurchaseDetails(); return;
        }
        java.util.List<MyLib.Agent> agents = ctx.getAgents();
        if (agents.isEmpty()) { showMsg("No agents available."); return; }

        MyLib.Agent assignedAgent = agents.get(0);
        MyLib.Discount disc = buildPurchaseDiscount();

        MyLib.Transaction txn = new MyLib.Transaction(buyer, lot, null, disc);
        txn.setTransactionType("RESERVE");   // auto-sets reservedUntil = today + 30 days
        txn.setTransactionStatus(MyLib.Status.RESERVED);
        txn.setAssignedAgent(assignedAgent);

        lot.updateStatus(MyLib.Status.RESERVED);
        buyer.addTransaction(txn);
        assignedAgent.addPendingTransaction(txn);
        ctx.addTransaction(txn);

        showMsg("Reserved! Block " + blk + " Lot " + lotNum
            + " is reserved until " + txn.getReservedUntil() + ".");

        jComboBox_selBlock.setSelectedIndex(0);
        jCheckBox_senior.setSelected(false);
        jCheckBox_pwd.setSelected(false);
        jCheckBox_firstTime.setSelected(false);
        jCheckBox_veteran.setSelected(false);
        populateBrowseTable(buyer.viewAvailableLots());
        refreshBuyerTxnTable();
        mainTabs.setSelectedIndex(2);
    }

    private MyLib.PaymentMethod buildPurchasePaymentMethod(int loanTerm, MyLib.Lot lot) {
        String method = (String) jComboBox_payMethod.getSelectedItem();
        switch (method) {
            case "Bank":           return new MyLib.Bank(0);
            case "Pag-IBIG":       return new MyLib.Pagibig("PAGIBIG-000", "Housing", 0);
            case "EMI (In-House)": return new MyLib.EMI("EMI-" + System.currentTimeMillis(),
                                           loanTerm, lot.getHouseModel());
            default:               return new MyLib.Cash(0);
        }
    }

    // ── My Transactions helpers ─────────────────────────────────────────────

    private void refreshBuyerTxnTable() {
        javax.swing.table.DefaultTableModel m = (javax.swing.table.DefaultTableModel) buyerTxnTable.getModel();
        m.setRowCount(0);
        for (MyLib.Transaction t : buyer.viewMyTransactions()) {
            MyLib.Lot lot = t.getLot();
            String reservedUntil = "RESERVE".equals(t.getTransactionType()) && t.getReservedUntil() != null
                    ? t.getReservedUntil() : "\u2014";
            m.addRow(new Object[]{
                t.getTransactionID(),
                lot != null ? lot.getBlkNum() : "\u2014",
                lot != null ? lot.getLotNum() : "\u2014",
                lot != null && lot.getHouseModel() != null ? lot.getHouseModel().getModelName() : "\u2014",
                "\u20b1" + String.format("%,.2f", t.getFinalTCP()),
                paymentLabel(t.getPaymentMethod()),
                t.getLoanTerm() > 0 ? t.getLoanTerm() + " yr" : "\u2014",
                t.getTransactionStatus(),
                reservedUntil,
                t.getAssignedAgent() != null ? t.getAssignedAgent().getName() : "\u2014",
                t.getRemark() != null && !t.getRemark().isEmpty() ? t.getRemark() : "\u2014"
            });
        }
    }

    // ── Shared helpers ──────────────────────────────────────────────────────

    private void styleTable(javax.swing.JTable t) {
        t.setRowHeight(26);
        t.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        t.setSelectionBackground(new java.awt.Color(210, 228, 252));
        t.setGridColor(new java.awt.Color(220, 220, 220));
        t.setShowGrid(true);
        t.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        t.getTableHeader().setBackground(HEADER_COLOR);
        t.getTableHeader().setForeground(java.awt.Color.WHITE);
        t.getTableHeader().setReorderingAllowed(false);
    }

    private void setColWidths(javax.swing.JTable t, int... widths) {
        for (int i = 0; i < widths.length && i < t.getColumnCount(); i++)
            t.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
    }

    private javax.swing.table.DefaultTableCellRenderer statusColorRenderer(int statusCol) {
        return new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable tbl, Object val, boolean sel, boolean foc, int row, int col) {
                super.getTableCellRendererComponent(tbl, val, sel, foc, row, col);
                if (!sel) setBackground(row % 2 == 0 ? java.awt.Color.WHITE : new java.awt.Color(240, 245, 252));
                if (col == statusCol && val != null) {
                    switch (val.toString()) {
                        case "AVAILABLE": setForeground(new java.awt.Color(0, 130, 0)); break;
                        case "PENDING":   setForeground(java.awt.Color.DARK_GRAY); break;
                        case "SUBMITTED": setForeground(new java.awt.Color(0, 80, 200)); break;
                        case "RESERVED":  setForeground(new java.awt.Color(180, 110, 0)); break;
                        case "COMPLETED": setForeground(new java.awt.Color(0, 130, 0)); break;
                        case "CANCELLED": setForeground(new java.awt.Color(120, 120, 120)); break;
                        case "REJECTED":  setForeground(new java.awt.Color(180, 0, 0)); break;
                        default:          setForeground(java.awt.Color.DARK_GRAY); break;
                    }
                } else { setForeground(java.awt.Color.DARK_GRAY); }
                return this;
            }
        };
    }

    private String paymentLabel(MyLib.PaymentMethod pm) {
        if (pm == null)                  return "\u2014";
        if (pm instanceof MyLib.Cash)    return "Cash";
        if (pm instanceof MyLib.Bank)    return "Bank Financing";
        if (pm instanceof MyLib.Pagibig) return "Pag-IBIG";
        if (pm instanceof MyLib.EMI)     return "EMI (In-House)";
        return pm.getClass().getSimpleName();
    }

    private double parseSafe(String s, double def) {
        try { return Double.parseDouble(s.trim()); } catch (NumberFormatException ex) { return def; }
    }

    private void showMsg(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable browseLotTable;
    private javax.swing.JComboBox buyerBlockCombo;
    private javax.swing.JTextField buyerBudgetField;
    private javax.swing.JTable buyerTxnTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_applyFilter;
    private javax.swing.JButton jButton_refreshTxns;
    private javax.swing.JButton jButton_reserve;
    private javax.swing.JButton jButton_selectLot;
    private javax.swing.JButton jButton_showAll;
    private javax.swing.JButton jButton_submitToAgent;
    private javax.swing.JCheckBox jCheckBox_firstTime;
    private javax.swing.JCheckBox jCheckBox_pwd;
    private javax.swing.JCheckBox jCheckBox_senior;
    private javax.swing.JCheckBox jCheckBox_veteran;
    private javax.swing.JComboBox jComboBox_loanTerm;
    private javax.swing.JComboBox jComboBox_payMethod;
    private javax.swing.JComboBox jComboBox_selBlock;
    private javax.swing.JComboBox jComboBox_selLot;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_blk;
    private javax.swing.JLabel jLabel_blockFilter;
    private javax.swing.JLabel jLabel_discAmtKey;
    private javax.swing.JLabel jLabel_discHeader;
    private javax.swing.JLabel jLabel_discountAmt;
    private javax.swing.JLabel jLabel_downPayKey;
    private javax.swing.JLabel jLabel_downPayment;
    private javax.swing.JLabel jLabel_dpPeriod;
    private javax.swing.JLabel jLabel_dpPeriodKey;
    private javax.swing.JLabel jLabel_dpTarget;
    private javax.swing.JLabel jLabel_dpTargetKey;
    private javax.swing.JLabel jLabel_finalTcp;
    private javax.swing.JLabel jLabel_finalTcpKey;
    private javax.swing.JLabel jLabel_floorAreaFilter;
    private javax.swing.JLabel jLabel_interestKey;
    private javax.swing.JLabel jLabel_interestRate;
    private javax.swing.JLabel jLabel_loanTerm;
    private javax.swing.JLabel jLabel_lot;
    private javax.swing.JLabel jLabel_lotAreaFilter;
    private javax.swing.JLabel jLabel_maxBudget;
    private javax.swing.JLabel jLabel_modelName;
    private javax.swing.JLabel jLabel_monthlyAmort;
    private javax.swing.JLabel jLabel_monthlyKey;
    private javax.swing.JLabel jLabel_payHeader;
    private javax.swing.JLabel jLabel_payMethod;
    private javax.swing.JLabel jLabel_resFee;
    private javax.swing.JLabel jLabel_resFeeKey;
    private javax.swing.JLabel jLabel_selLotHeader;
    private javax.swing.JLabel jLabel_tcp;
    private javax.swing.JLabel jLabel_tcpKey;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_browse;
    private javax.swing.JPanel jPanel_browseFilter;
    private javax.swing.JPanel jPanel_browseSouth;
    private javax.swing.JPanel jPanel_detailGrid;
    private javax.swing.JPanel jPanel_myTxns;
    private javax.swing.JPanel jPanel_purchase;
    private javax.swing.JPanel jPanel_purchaseDetail;
    private javax.swing.JPanel jPanel_purchaseLeft;
    private javax.swing.JPanel jPanel_txnToolbar;
    private javax.swing.JScrollPane jScrollPane_amort;
    private javax.swing.JScrollPane jScrollPane_browse;
    private javax.swing.JScrollPane jScrollPane_buyerTxns;
    private javax.swing.JScrollPane jScrollPane_purchaseLeft;
    private javax.swing.JSplitPane jSplitPane_purchase;
    private javax.swing.JTable jTable_amortTable;
    private javax.swing.JTextField jTextField_floorArea;
    private javax.swing.JTextField jTextField_lotArea;
    private javax.swing.JTabbedPane mainTabs;
    // End of variables declaration//GEN-END:variables
}
