/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;
/**
 *
 * @author Jrebe
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        addRegisterButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        USER = new javax.swing.JTextField();
        PASS = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 246));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LUMINA HOMES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("STXihei", 1, 36)); // NOI18N
        jLabel2.setText("WELCOME TO LUMINA HOMES");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("USERNAME:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("PASSWORD:");

        USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 91, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PASS, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = USER.getText().trim();
        String password = new String(PASS.getPassword());
        if (username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter your credentials.");
            return;
        }
        AppContext ctx = AppContext.getInstance();
        MyLib.User user = ctx.authenticate(username, password, "Admin");
        if (user == null) user = ctx.authenticate(username, password, "Agent");
        if (user == null) user = ctx.authenticate(username, password, "Buyer");
        if (user == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Denied Access");
            return;
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Login Accepted");
        if (user instanceof MyLib.Buyer) {
            new BuyerFrame((MyLib.Buyer) user).setVisible(true);
        } else if (user instanceof MyLib.Agent) {
            new AgentFrame((MyLib.Agent) user).setVisible(true);
        } else if (user instanceof MyLib.Admin) {
            new AdminFrame((MyLib.Admin) user).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addRegisterButton() {
        javax.swing.JButton regBtn = new javax.swing.JButton("REGISTER");
        regBtn.setFont(new java.awt.Font("Segoe UI", 0, 18));
        regBtn.addActionListener(e -> showRegisterDialog());
        javax.swing.JPanel regPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        regPanel.setBackground(new java.awt.Color(255, 255, 246));
        regPanel.add(regBtn);
        java.awt.Container cp = getContentPane();
        cp.setLayout(new java.awt.BorderLayout());
        cp.add(jPanel1, java.awt.BorderLayout.CENTER);
        cp.add(regPanel, java.awt.BorderLayout.SOUTH);
        pack();
    }

    private void showRegisterDialog() {
        javax.swing.JDialog dlg = new javax.swing.JDialog(this, "Register New Account", true);
        dlg.setSize(420, 380);
        dlg.setLocationRelativeTo(this);
        dlg.setLayout(new java.awt.BorderLayout());

        javax.swing.JPanel form = new javax.swing.JPanel(new java.awt.GridLayout(0, 2, 8, 10));
        form.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 24, 10, 24));

        javax.swing.JTextField  nameF   = new javax.swing.JTextField();
        javax.swing.JTextField  emailF  = new javax.swing.JTextField();
        javax.swing.JPasswordField passF = new javax.swing.JPasswordField();
        javax.swing.JComboBox<String> roleC = new javax.swing.JComboBox<>(new String[]{"Agent", "Buyer"});
        javax.swing.JTextField  budgetF = new javax.swing.JTextField("1000000");
        javax.swing.JTextField  commF   = new javax.swing.JTextField("0.05");
        javax.swing.JLabel budgetLbl = new javax.swing.JLabel("Budget (Php):");
        javax.swing.JLabel commLbl   = new javax.swing.JLabel("Commission Rate:");

        roleC.addActionListener(e -> {
            boolean isBuyer = "Buyer".equals(roleC.getSelectedItem());
            budgetLbl.setVisible(isBuyer); budgetF.setVisible(isBuyer);
            commLbl.setVisible(!isBuyer);  commF.setVisible(!isBuyer);
        });
        commLbl.setVisible(false);
        commF.setVisible(false);

        form.add(new javax.swing.JLabel("Full Name:"));   form.add(nameF);
        form.add(new javax.swing.JLabel("Email:"));       form.add(emailF);
        form.add(new javax.swing.JLabel("Password:"));    form.add(passF);
        form.add(new javax.swing.JLabel("Register As:")); form.add(roleC);
        form.add(budgetLbl);                               form.add(budgetF);
        form.add(commLbl);                                 form.add(commF);

        javax.swing.JButton submit = new javax.swing.JButton("Register");
        submit.addActionListener(e -> {
            String name  = nameF.getText().trim();
            String email = emailF.getText().trim();
            String pass  = new String(passF.getPassword());
            String role  = (String) roleC.getSelectedItem();
            if (name.isEmpty() || email.isEmpty() || pass.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(dlg, "All fields are required.");
                return;
            }
            AppContext ctx = AppContext.getInstance();
            if ("Buyer".equals(role)) {
                double budget = parseSafe(budgetF.getText(), 1_000_000);
                String id = "BUY" + String.format("%03d", ctx.getBuyers().size() + 1);
                ctx.registerBuyer(new MyLib.Buyer(name, email, pass, id, budget,
                        MyLib.BuyerType.REGULAR, ctx.getSubdivision()));
            } else {
                double comm = parseSafe(commF.getText(), 0.05);
                String id = "AGT" + String.format("%03d", ctx.getAgents().size() + 1);
                ctx.registerAgent(new MyLib.Agent(name, email, pass, id, comm, ctx.getSubdivision()));
            }
            javax.swing.JOptionPane.showMessageDialog(dlg, "Registration successful! You may now log in.");
            dlg.dispose();
        });

        javax.swing.JPanel btnRow = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        btnRow.add(submit);
        dlg.add(form, java.awt.BorderLayout.CENTER);
        dlg.add(btnRow, java.awt.BorderLayout.SOUTH);
        dlg.setVisible(true);
    }

    private double parseSafe(String text, double def) {
        try { return Double.parseDouble(text.trim()); } catch (NumberFormatException e) { return def; }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PASS;
    private javax.swing.JTextField USER;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
